creation_rules:
  # Encrypt with Age key
  - path_regex: config/private.*\.ya?ml$
    age: >-
      age172unqujv5uv885spfc8gk7ztru9y2lc3jgr20s3gpt9lzhtt8gusgzusdn
      age13ae2q6s6f8talcfvvnzm6qzfhcecytr506g9xh6mnjpteecjd98qw9qvq5
