#ENC[AES256_GCM,data:oChOp2zsJS9VV7snvi4q0KdzNbyHWHm9XXNNe8KMWUEjkORUL3ocEVbyCZhtBPo81l+SujcCyn1JphcM8gPJbhZs,iv:0SVBezaA5BDvGKDcPmELNMg4UkDRT7LsQps5Kuo2WZU=,tag:OCsCBercs3INGQSOlgTqGA==,type:comment]
#ENC[AES256_GCM,data:qoZiGPqvc6XYl0caauXNzE2orlIFrCXMYWYphcx75o8SoT6aoar0Kth3w8BqymT9M2nXow==,iv:9DxmQthEKmMQ39Znu8OOv57/aTUYPo0XWozEDg3BEgE=,tag:p3mc7IFkqV2insoNlaYveA==,type:comment]
#ENC[AES256_GCM,data:bPS5udFaxibZR9dh6s3LE9c3UxaLFO8aS56n9T0oGzK9GDsZD1wZeO0tfYuqJXpuUHWQTKXnhIjpjCmZ2P+36jb+,iv:nYdfuDlBCwBl+dSvnhzFRa1+SNJnNRlhTlfp8Upa7d8=,tag:yzDxpiE1Io9dTXDmNiGDRg==,type:comment]
#ENC[AES256_GCM,data:AjxxsY1rs7k9Z4DOJF3KUV5mTFIZSv8qoYWnlMewoyJNkiwVmiUwRr2r333ePoTPZ9r3OACCDLpmTdoP5whqzFw=,iv:PGwyMEr0drx1HJALx7oKFC1HcxsePl5JJXRJyE2rjHw=,tag:3+HImK14Iv6B8CgFj5XPlA==,type:comment]
#ENC[AES256_GCM,data:vkAzHtWw8mkf+aG8f727bNpBQIF+Pqfol6AeAYQsxqZ7ANa/SYJH/Nt+MCY2kYV6CWWlB8jGoo3LXeVtBptsfbU=,iv:fMdJYBljrmoiukL2oVsqyFWZnRENX/61ul09SykQ6sI=,tag:KF5vH1fEGexxuKy57xlZhA==,type:comment]
#ENC[AES256_GCM,data:afEBFQBstfDSOcCTwTRnfAvO8+d+58RkNS5zTVW73AOgi7ZTAXADJ7fp9z10BCPc3nO7pmNSg6+idKBqVS8Yd6cd,iv:cgd5hyVh4p2Lo6xOTA22gBzjemOh2xqENXeGXo/gKY4=,tag:yFI916/PFQ+ZNKfvQUhW/Q==,type:comment]
#ENC[AES256_GCM,data:7qF5l5mL64TZ7HLDC+JQneIlGLoVAs/Y+iEMY4GSNxctCjmb,iv:G4QU1ZF8RNkBN0m4aJ5Q0Bf/8DYCwrTndRTjQMni0W8=,tag:b7BWqOt7ANyWSKTXD+4gNw==,type:comment]
#ENC[AES256_GCM,data:E0BQTmyMzKT6rBe0p2xpfqN2jw2TmIo=,iv:899tUql4y2fNnFGW+N0MiUA9UgwpQ5qi1BH8prkAicc=,tag:lngLwLN3XRcJcmpqzmbZIg==,type:comment]
git_user:
    name: ENC[AES256_GCM,data:e0G7gJ0cOtyqig==,iv:QaJCUiZPmM/boursCNmFWeHHjIsxLWdmPcGP+Zlw+8U=,tag:Yrg9tfnN1KZxbpnBJtaxGA==,type:str]
    email: ENC[AES256_GCM,data:WJDQQpI2BeILaB7ACPRTW/i06nOvTDa1P68bfTUK6fxLbQQ=,iv:OiM4JWJYTGbl3vZ7K4q1WsUYdaeQBDhph8qvdYFQDkA=,tag:CmB+OEBcZYSr7LT/3FQNiA==,type:str]
    #ENC[AES256_GCM,data:7GC+XkeySkQpyRBdxYux4gFaYcmToVZRMGZa56l0Me1CMpw+lnt/EaVaWbbz32GndfRy,iv:S6DEAUP/+ApwGeQLCxTbiwx1rUzxjm+qieoPwBoCE4o=,tag:5N9pH20jbTB792JaxwKsOQ==,type:comment]
    signing_key: ""
#ENC[AES256_GCM,data:NqLnrK44DjiRbxAd0YtzFRom,iv:5DIuktbSGb4l56i13NZtBJ6BMKZY34rvKzuULaOTCE0=,tag:XZQVQlAZuzmwcXtYndL5hg==,type:comment]
ssh:
    #ENC[AES256_GCM,data:9uueps3XT3Yxnbj4h+cvKvugipPyMgC0pBKvHSMj8OaTUR+h,iv:E7ClkZjOu0iSEpb+h7zOEtSruYr6BrM4eBJAlUe6Hww=,tag:ZutkvM9C/5jvHMHKRJtEKg==,type:comment]
    generate_key: ENC[AES256_GCM,data:CXJaLg==,iv:b6edHEIwBZWpseuo6ByK+a65L8o1D/b2s82TPJofz/E=,tag:Mq63exCIeAod8bYSc9CWeQ==,type:bool]
    #ENC[AES256_GCM,data:q5ImWRjHshPSW0+3d+e2x9Py5WUe5Q==,iv:Mz0TOTXtbQeg2+uMNl9PDwHKqUZeVPiMtwPX3A8JShY=,tag:RzPjTUEzIRyInc+Jfd2xoQ==,type:comment]
    key_type: ENC[AES256_GCM,data:La6Uzk8F5A==,iv:BpQR7+BOg/m5LaiUDcqtnOM03K8eu/elvuZGQdMLGFk=,tag:Uc5qKQcPFqRRWmhed06A2g==,type:str]
    #ENC[AES256_GCM,data:bm7j7nyGivTsLEH5InvSk6TBucO+BQ==,iv:d4RpbAnszjmk735T91MmN51krTEsMd37Tu1hsQtnoEk=,tag:O70RMspyZKI9CnfKpwmcHg==,type:comment]
    key_email: ENC[AES256_GCM,data:ep6e5ZEpVTqNqhtrbWTAZbXq00dT,iv:mPY69MjVGEMMGHAyaB76l5onRjGVLelS0kN2KNBEIlU=,tag:QiYDsA9AenKGdPgFnXCRMw==,type:str]
    #ENC[AES256_GCM,data:ntcTgBsNphfJkMspuVuzKNTXBxnF2dM4fRGrChQzVGL2hljsclpflAKP5EmA4Q/NVTaZr81XVF2LOhtxIbo/Yg==,iv:kdkkXwADYgar06bC1VAEKjrq8Ahbu+sCIR3cJFylupQ=,tag:Fp3Fceb4gDp6IUliqPyAsw==,type:comment]
    key_passphrase: ""
#ENC[AES256_GCM,data:gNybB9NQSmNjccqDruH8d55n7cN0,iv:AKAMVlZly5MBGDNLUfGQskfNic0t7L4V7Zkc8cvjM88=,tag:yQzvypjrm7C+y0kt2CLNXA==,type:comment]
github:
    #ENC[AES256_GCM,data:ykvwKqb+JiCyasKBy765atwDwYgC,iv:nPDQUXHvQmZNJESOV7B1fErCjjyGlMfP3TeZMKDFktQ=,tag:MYxSdOyJwBWF3hnqNQSNrg==,type:comment]
    username: ENC[AES256_GCM,data:5/MJ4LPqu3Bz8g==,iv:IZi6PKzpjtUUJNefalvQXII8A8zZJzXTo2umfbCtGW0=,tag:0Ko/FL39DVAcm4ZOAj3fCw==,type:str]
    #ENC[AES256_GCM,data:/jVWC1tx+v6r8gcwZv4jMzONNeh0qh1YtG6tOUUduTdzkxGUKVRgAcc=,iv:hXAhjQk0JUBZNOoIU8IX2ay/sgLS8dbWLmoxZIDxrlg=,tag:+bGdVJG2i/AhNgHk1pG7WQ==,type:comment]
    upload_key: ENC[AES256_GCM,data:BbdLmg==,iv:d9i5qOhaQxbKqzxgQngyvXxNS+U3ubnWFOTtdY82MR0=,tag:u3chcl81GbDjB7OjvRk6/g==,type:bool]
    #ENC[AES256_GCM,data:1ZkrWQ8M/ddIplVkuMHaYNLWDdoes72Qy7VEg/LHBwO2dSxwsRl5ClP0KFlF8VpLoqSx,iv:sQE2JXI/FifBSM0RWYuntGzjO2k5OaYzU9fd6KeyFj0=,tag:6Q2o/wa2Zw+RDUN0RtWqCg==,type:comment]
    #ENC[AES256_GCM,data:LJCI1gJUztB4VcDQT6OnkS7A6Uogg0gZchlxbLfUqyhbembm,iv:p+0vZA1o2bRM8lPJA8fNmcR4YW559UQqd9/p5GLR+d0=,tag:IQhP/HANWAlMg5v/2ZzIPA==,type:comment]
    access_token: ENC[AES256_GCM,data:ws9v38goLJvMnGbpO3KMCAgqkGfVgLDKaK/NllTZR3pNL1/2BVSp02mpljYwOiJ+ofI3s/F/UJXCc+guA627IAlbCcS4NjiotKYTkQFrJzcudRKDYigfR76zgERf,iv:bGiWp6Qn1HlCYYK7dqW2ybEO5D5jfWX1SyRsHx1ZXSc=,tag:a8X39TeVt4Rq46XGqAZ+7w==,type:str]
    docker_repo:
        #ENC[AES256_GCM,data:yY5vOBwFqmq4fU2hyGUJtYmCOcZkOGlpeflxdG3nODfq/yAVMwJhO6zmGAwLeGPCRmsYFea+XQEPI+DvxDz+FA3OEYQNBA==,iv:RYJhF3Be3LdKXluR5zzJjI7k8Tbpzkzjh/cPTRmkQk8=,tag:HxF5S0jVMstVBlMDwFhifA==,type:comment]
        url: ENC[AES256_GCM,data:jaZT6X9anz8zYRnUjF0d9bvTM3frq+oA/hnPi7EwsnrROtCxZ93C84DVr0tukg==,iv:nlcbrLnHuZhafkVnj/FVbKRTDTd98qaZmFR7z7dMzEo=,tag:hs0cNSW+YQ0jRub65YXSwQ==,type:str]
        #ENC[AES256_GCM,data:fQjvhp+P63I8YNOQVKoRCEGKZwCyMXRP+nES8R0EHedpkbi3EzEeDXmWn6EuYzTzig==,iv:BF/leluBs+TS5RPdKVuiipO1hk4dmQTwawhZuHBBi3A=,tag:ww67hfed6y1Q2M5jsm+2Bw==,type:comment]
        branch: ENC[AES256_GCM,data:Voq0+A==,iv:W72uAmp76lD3oml0MyMUCmhuw3/L8juX5IJhK9p4rG0=,tag:bSCNglKHJSgx9DHPYDODKw==,type:str]
        #ENC[AES256_GCM,data:zFDlQ0Ncld//ZuwPuYE1YcMj7H8OULR13yZnfrQvbXU/lvm5wnjrgPZXRDho9xGcOCfVYA==,iv:QHPpq9bKCnhD+fEvib7CzrymkrkQrT6bROhNxQwjiJU=,tag:YVfPL9Fm6CnM0tgqm9dv1w==,type:comment]
        #ENC[AES256_GCM,data:8GzSaUmtpgeP1gjsKFECYEe+sKir1IbMTYdbLJClD/R2Jwxq5WMhahZA0v228kpk/uy2exX571km6w==,iv:F4QtiZ7eYx9lzdIYbxb+sKG6Dyecs9Xj2g3g93YFv1U=,tag:RBdvjvhnkuFVo8JECPEbGQ==,type:comment]
        directory: ENC[AES256_GCM,data:PQWZZoxZbO2wcTORbg==,iv:f6EBLaU+tqeAJBpEkQBgt4/Rhby6tSjDIAIHgAHg8Ro=,tag:a4cpvRPAUZOoBlMrb4+0lw==,type:str]
        #ENC[AES256_GCM,data:GLqaYXKn7gt6ENXF6vSrtGRWAW2wDaHdqdQ+RlKw0a1/AeEh1Qg8QcBfLXt10n4Wrwaiuuhhy+N3FDFHM6LA3cTYVno=,iv:Wz3l9xwycCF7ubUtk/iymcGObbsLS02NGIkXkjV0HF0=,tag:9luGMtAdGx+PzTz018y7Mg==,type:comment]
        auto_update: ENC[AES256_GCM,data:6bPXOg==,iv:XhEX9nO1vbvhbYwni06bNNtz+jvGchgwu4BZgF6TYII=,tag:RsabwFEPKMjtTNLi41m7Tw==,type:bool]
#ENC[AES256_GCM,data:bWcqFgZ7CAwM8OrK8dg0,iv:RjiZ2CzedUJ1y5doyt20mVn80oiHEQWROiDNVFQuMOs=,tag:8UcLR+lHD2E4LiuthegSvg==,type:comment]
network_mounts:
    - type: ENC[AES256_GCM,data:xpLj,iv:tcZchc5xeNmaGSqi1NoxFKzMPyHmT5WXyhaur0lbkko=,tag:m7biGVAPGirw2nfypr4K2w==,type:str]
      source: ENC[AES256_GCM,data:fk3fnqtDkSFh+srALditKAmLGyps,iv:Jri2QICkUM6L6qyY6QXIyQWWONSEkLpd9j3qa+oTHG4=,tag:ftoOzrGPJoQRirAsy9RE3Q==,type:str]
      target: ENC[AES256_GCM,data:bhoKPknw+ISJu80=,iv:gxwDCA6ly7KL23HHpF0v853mtuB24vAE/bvkwryVreM=,tag:69K1Gx4GeU+rhsWXdnb0Xg==,type:str]
      options:
        - ENC[AES256_GCM,data:orrP07YK,iv:+KnL49VR75X5sVhPK86dfDlgDD0nVS3O0o2C+6ki/dw=,tag:TGpVqQp76nG55HjPOfe9Og==,type:str]
        - ENC[AES256_GCM,data:/INYWfv+,iv:Un2w4MTc5onPg9j6kIQT9kkNZiVxfusmOlgwKaUSoPk=,tag:OEnAEG0J0eHMqJfeJIuF+A==,type:str]
        - ENC[AES256_GCM,data:v7nkaW9WoA==,iv:5fMwHIaf+7h3pJHd0C/KtNuDqCZSTtEcPSsXTMnENqA=,tag:DpROiWW57GCKWIHcVO887Q==,type:str]
        - ENC[AES256_GCM,data:cOfb9g==,iv:i+/9jsWBB75v7lee3j+bD8SOZf+UKlnAGYxOXFAzpo8=,tag:LbQNM84W78KO3J8KVNab2Q==,type:str]
        - ENC[AES256_GCM,data:0dvYbQTdwbw=,iv:iOSF+mnzhallnYIMIhZSX/bDjrUggOVNttyQsIPAcu8=,tag:uLDBwp89cH2u2UsChPTJxA==,type:str]
        - ENC[AES256_GCM,data:vW9x/Mrbhg==,iv:ldfk7SBO0d2ClKhhGkcEKt8Mf4YpdLMXcTN288KGjVo=,tag:iH7/Iftjkvha8uvXPETomA==,type:str]
        - ENC[AES256_GCM,data:cJMnlLia2V/A7H9ea1l/V8JAdA==,iv:6IF4yKbo49ig8eXOIzlXlYuq56S9mOLVcv2lsbDDum0=,tag:OuBrOFvhjtjGh0iTLXWeDw==,type:str]
        - ENC[AES256_GCM,data:s4xPxWULKe7+dvIRWSyOs91bUYbs6NlSBg==,iv:a/5lePrHZq4Xyzpw3N1NssnlhdxzdfLOBblRc+j/S8c=,tag:/gj8zrnvkMt53N2T5bV5wA==,type:str]
        - ENC[AES256_GCM,data:LVA=,iv:CycFfcZBZlkoIuH3rgFHAkIeN/wl/bRejW4wmMqsxCo=,tag:pb9Bzoc+Huj5kVoU9GZERA==,type:str]
      dump: ENC[AES256_GCM,data:NQ==,iv:rZU14EKpebE8sqnNcm71s+kF3CqP54vzh6Eb6Sqe0U0=,tag:QaFgKQkblORwPtYk55z1wA==,type:int]
      fsck: ENC[AES256_GCM,data:6g==,iv:xBBnSnTW9DE572oeHNYaGpjc0+tSxA21XktB08SdaUw=,tag:jcf27YikESRxS0+kSA+V6A==,type:int]
      permissions:
        mode: ENC[AES256_GCM,data:JbvH,iv:66JoxpI6t41fUS9GqBG9ibzD+hqazKgKEyvunhNzJB4=,tag:cJAG7qPasQ5uJub6dUOSPA==,type:str]
        owner: ENC[AES256_GCM,data:sYa9PA==,iv:uc7f0uTGd9PbE7aY08uG86XGSLzsQPdyUMO8sBryia0=,tag:rZJPnUJs+zP1vic/0wxGoA==,type:str]
        group: ENC[AES256_GCM,data:xcC8huKa,iv:skITNyIppvLw5s1wUpFHZa5lfz27Wba2BAJV0Nl5KUg=,tag:LIaH30YQY31wJPwdE0PGEQ==,type:str]
    - type: ENC[AES256_GCM,data:rZHp,iv:LeDgWxhFo9SFEbM0BQrOxRcNNH9b3dSlDRhmWBr5sVc=,tag:W/BtPqdn01GrjV12OHcaBQ==,type:str]
      source: ENC[AES256_GCM,data:cLp877KZNMtXSIO/fWiqhm3O+h/rbA==,iv:E12gObHAJDs7D8YXfhgIrGu07rWLR1LbQYrfxjPs10c=,tag:S/KLzoLsnscjs+N0A+d9LQ==,type:str]
      target: ENC[AES256_GCM,data:3K0yy4iLZjMpEz+I,iv:W2RyFN/5u7y+NGFfwnoKg61Kyu9UVmpM8xBd0Bb+UDM=,tag:A1pJWDKYdTZkdkw7ura9ug==,type:str]
      options:
        - ENC[AES256_GCM,data:5rARkktd,iv:kjNb+1fn2SLwu8iOsLP8T93/kkF22Tt2tRUZgyUypIo=,tag:st1Vyb4sdQCLcw6wttQM2Q==,type:str]
        - ENC[AES256_GCM,data:tDFLKS+O,iv:hJC3DrVmc2Bt6j/dgQR4AU5MIFXAQ4pAreNL0ztYb9o=,tag:eYQA82COtWtciIGQo5u4xA==,type:str]
        - ENC[AES256_GCM,data:YQ4yM/ZPtA==,iv:kH2Y8eJ7sBlwzWsZ+4rvuo0ggD2vNH9R/yqBaHE1XdA=,tag:AUp9fkMCRRHUJXAV9hyfjA==,type:str]
        - ENC[AES256_GCM,data:snCfgw==,iv:LN2pO25PF7Q9Y2ugtbEiobzV8vJur93WB5PI4e+wOa0=,tag:C7gminYKKLi/x9mHSvTYFw==,type:str]
        - ENC[AES256_GCM,data:fEICg4ajgRk=,iv:sJTRST5tbEC0VYZ/tkThhonyoTBPzoKJcJFyLAb9hks=,tag:RtYr8I4UZYoxjTIHhPEWvQ==,type:str]
        - ENC[AES256_GCM,data:mwuJd3nQWg==,iv:b9fCa0/j+kuSg1JDyLd2UYLeqCsMcAFQsY9vqDMlsVw=,tag:BG/ZwxmnRzMokMZkfqdAdA==,type:str]
        - ENC[AES256_GCM,data:ItXOayco2AXyVYci5+02scz/pw==,iv:G8cbUmvamELzu3lyIsCk3CYAti6KJq1YHLjGTv5MwHE=,tag:peO9f1MqWiUeJ2cpOUrKmQ==,type:str]
        - ENC[AES256_GCM,data:X5IDjLni7ImXWy843fC5RQ96R0CPWnKcpA==,iv:SWp7XMQYyWzvP4wDKOEeGs6825gZgApZzi1SLMN9QdQ=,tag:K4+eu9eC9kALcV/b1sJXYQ==,type:str]
        - ENC[AES256_GCM,data:xsU=,iv:cVKIvAzf2xpigFYweNHD1DsDoNV+6bnWLw3S2GyP6lg=,tag:qxV2N4KOe9FTHnn1jCAipw==,type:str]
      dump: ENC[AES256_GCM,data:tQ==,iv:X5jJg8iHh8Gn+wi1GGyNk962501TpKkGf1cNeDdS9Ug=,tag:dztwmtk4nsls7aXWB7PqeQ==,type:int]
      fsck: ENC[AES256_GCM,data:aw==,iv:XAKJ+TfKRH5qjxLuzXh0DVNyLcUwhcWTbQofwQpp6+w=,tag:V74xzZNVYjeyZKwB3xH32A==,type:int]
      permissions:
        mode: ENC[AES256_GCM,data:qVVM,iv:LH+OfRbvUEcaqCv4H3GT+d99q9jIJjCveOG2EZddVL8=,tag:wyHsuID4uvDAQQskKsJIDA==,type:str]
        owner: ENC[AES256_GCM,data:rsPb4A==,iv:tDtKPKoO84uOwQ/DsmgR2CyrPaX6CUPbvb2YuPD/aKI=,tag:0X/oazHzOz0b4j9/30+6xg==,type:str]
        group: ENC[AES256_GCM,data:qoiZSHtZ,iv:xJex0/FhcBmHxP2f9l0APB/ZmTHCv+bSYe596sTAKXY=,tag:iFVxbjgDgB056bZQN1+HUw==,type:str]
    - type: ENC[AES256_GCM,data:01Lz,iv:yOusp39SBoq8C9Cyar1eFcSIfNOoJsa/Idn95OrN4XU=,tag:yvwJrqSMUMPE4fC4rO4Jcw==,type:str]
      source: ENC[AES256_GCM,data:hAr5oYzkdS6EaRNNmK9SXQc=,iv:A6aTSJWbDS/NGONzNwKE5ZIm/QAcDZlQO9KFiYpLMfY=,tag:AbdSFSNtTGc7TxASo6faUw==,type:str]
      target: ENC[AES256_GCM,data:7XRdYsZqi+NPDUOC1TLPsLoE,iv:Cql7B1Ii/GZ7fVYGhQqBeGuXulGNR/QF5cgcDyIlp5E=,tag:ThS3G78slpv1f7ZZiftsEA==,type:str]
      options:
        - ENC[AES256_GCM,data:Ph9QqxiE,iv:grU/wm/ZhruwiAO3rBKPdLQjkgKwiGQnjXPsZUWovgY=,tag:vetLiQyj9kQmMzLeYhVp8A==,type:str]
        - ENC[AES256_GCM,data:hFcLvgUL,iv:xLiXKFCbYzdkRd2oXxjKhLRLWRLk20IjADttwPLBNY8=,tag:6F6NigErfobG549k0jdLqw==,type:str]
        - ENC[AES256_GCM,data:1eTXfYpRnA==,iv:NE0i964jZNkZI6UzdgoSfdCHoTevYMFkF02m8DUyO4k=,tag:fkKc7pzeOX2TAtNC2Ja9ew==,type:str]
        - ENC[AES256_GCM,data:hgLHyg==,iv:OhxM2juAh6SwigZGzTygO87mTa46a33Vnt5bFI992RQ=,tag:tTQT8erse5tXzqY9ag3Pfg==,type:str]
        - ENC[AES256_GCM,data:ytvLZ+xrtv8=,iv:wUYbLyfhTZub0akHH6DiY7vQQgOsjbQGJNTpEFORPyU=,tag:ME8x818IbCGnlFkrrDzzMQ==,type:str]
        - ENC[AES256_GCM,data:t0zEcbGJhw==,iv:6GWnUIYQ1CDEmgmjSvX/gI0YA3aILgsr1elMDGUd9kY=,tag:xbreg7iPgfsT8AQTq4Ce4A==,type:str]
        - ENC[AES256_GCM,data:JltmTYlisw57nmFYpcUzKjW8hw==,iv:QZ5pKVphupZWGZoJqh7hTjEvvqlgzdUzJoxcpxsCPJA=,tag:La3Qw4uEIR4JKfJwru/i1A==,type:str]
        - ENC[AES256_GCM,data:a6BhJqBnu60coRSflDsz4sxgvXOQq2/qxQ==,iv:Dic3UW0NVPaipWCNiuZ6hUSAOGQ4ijzHmOJYhznzGoQ=,tag:CaR4wezgz0AybiHEMRayTg==,type:str]
        - ENC[AES256_GCM,data:ybw=,iv:05ep2X/Og/zptE9IgvmjPvqzWV1K9Xm0ZuKeKk9CNBw=,tag:ZQ1nvE5/n5flWv3y0kwVZw==,type:str]
      dump: ENC[AES256_GCM,data:RQ==,iv:uAU/9g8OqVCO9Cdx0i4LpY2LKVTa7LtRwu7PdC4n2l8=,tag:yF392lDxZJVYD/M1qEETWA==,type:int]
      fsck: ENC[AES256_GCM,data:eQ==,iv:nEGnvqaJf7OSJav+sCRjo5zTYY8IKib5w2gm68wwnk0=,tag:LicsSaHKAaiXrXxkdU1I+w==,type:int]
      permissions:
        mode: ENC[AES256_GCM,data:dZXs,iv:4saKI4tc29SDb06Ck9c7DTRRcWchzhx6TVQ9Pd71AaI=,tag:QjrW4JkqInOnsaoLQ9yGbg==,type:str]
        owner: ENC[AES256_GCM,data:n57Wbg==,iv:wORRlOen9KM7TfS8vzilIlo7lFRm2TJwlmJzoJcQqKY=,tag:SOtlq0CEqpeoAQi8KvtGTw==,type:str]
        group: ENC[AES256_GCM,data:ZRz/aAaD,iv:3rfhslylGvUrff7vVadl4YK3u2ngW4FvCIsHFHawl+Q=,tag:IyplL0RvYwwjX5yAEveMgw==,type:str]
    - type: ENC[AES256_GCM,data:lTi/,iv:dqZ6M/AlfaS87YwaE7uuVfB0Z7d1tBrJigK7ESqbg78=,tag:stu6b1saFORA4+cqmrpZuQ==,type:str]
      source: ENC[AES256_GCM,data:vjtpId81Sxwkzol8siFQuRWH,iv:ZqCgyNv0xrEHndlsvDHXQUItpfK18Hab1g9oxTh/mFk=,tag:aeNqZMLSW8/K2usK5Q+tfQ==,type:str]
      target: ENC[AES256_GCM,data:WIgT4/8xDjNezItg+Ce9IJ+hfA==,iv:Zkt8D4F+Yu6NEXAYawmtDb3XOupZTrEgwLvc+iDILW0=,tag:QZchpIMnA3fn7dn97RDGLw==,type:str]
      options:
        - ENC[AES256_GCM,data:qQrjvBhm,iv:j67XjxJmX/s66nGyCwLivn3ThjOZuJvGbZUexY9kAeM=,tag:M1bfae9r3EtKabLYgeYCHQ==,type:str]
        - ENC[AES256_GCM,data:Fw7kTkiX,iv:q514HtVsqbKaSfqErZPOqhhB6DT7tJB4k43IVZ1zsbw=,tag:vADnQOLf6iKjlgPoYwn+pw==,type:str]
        - ENC[AES256_GCM,data:wtaGi5Q9Xw==,iv:4SaI+Cgo+6Mfg60A/oV29GrAD8O49Lw77qZtkLlP/wg=,tag:an59xrXX3CmrnoeVZsg4Bg==,type:str]
        - ENC[AES256_GCM,data:1OygPQ==,iv:eqbXPBbnAWoe4h3Oz9gfNGbL6QLEw7ZgHneB0+IcJfc=,tag:3eBygKeTJCXaJD+/ewDxDQ==,type:str]
        - ENC[AES256_GCM,data:RqfRzA2ms1g=,iv:u+aS5xf16UFC9Deh/Rl6cymmOYfYKHTEu73puYPOyXo=,tag:jT2Eajpvv4m4NnaFP6nIOQ==,type:str]
        - ENC[AES256_GCM,data:XS0QEHJSTQ==,iv:zRIZOzT+DWiIOuu3zuANCX8pw56aEDOjsXgzEkJC5+M=,tag:Qajjt4jdOY9tjr1N5BHagA==,type:str]
        - ENC[AES256_GCM,data:YHxCY8GSGLcpnber7Zd7KgEpSg==,iv:MRKEPSB/ltk8qYTVRBRv4p2Cpr7NavlprLWL1FAFXys=,tag:lU3pTuGhus6VAVF2lcpgBg==,type:str]
        - ENC[AES256_GCM,data:CfKlWcuH9JQYhooXh+0Gzr3P4CcoLHG0vQ==,iv:HgppfDlH0PNAKbccTg7ihcg7biHKOTc6LiUD5i+NHQw=,tag:u+fqo3FOh8ww6etT1+YzuQ==,type:str]
        - ENC[AES256_GCM,data:iJE=,iv:7DB87ehqlEzp/n7nF+oR2fCUTDz3DJk1cM5VJXEQjUE=,tag:/i/cIbJ3Lf5Hxq5+KDcwIA==,type:str]
      dump: ENC[AES256_GCM,data:UQ==,iv:cbsqKYfmWfEn0Ya4IYSB5ZyuSa8y23CC4S6XkO17EPw=,tag:qRezI45x5PGEFIb4rHNTPw==,type:int]
      fsck: ENC[AES256_GCM,data:Xw==,iv:Aga6eMWHeFzucJDxQxY5Xk7Aa9h7WJ+zen4jZX83nM0=,tag:OQz+Ohm3hsi88QyowvFILw==,type:int]
      permissions:
        mode: ENC[AES256_GCM,data:aiQa,iv:NKi2TpkdMFCm8mEI4NeEV25fbiwJbmQ0QTvsvkadzlI=,tag:3rHq0X0D4elB/PqnmtNkOA==,type:str]
        owner: ENC[AES256_GCM,data:4GH7GA==,iv:Ibp9JqUrUeozKFQmMfILg8ib3Ze1NeH8JgSockrSzzA=,tag:jUpTccnlTmrFNC6Tdw34Og==,type:str]
        group: ENC[AES256_GCM,data:C1YBj/qe,iv:FaseUW0gYS3bV+jQgDKQ5z0eOKIPp2DPpZCjE17UYSQ=,tag:0DduOCQac9N5MIKxeeXQvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age172unqujv5uv885spfc8gk7ztru9y2lc3jgr20s3gpt9lzhtt8gusgzusdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTHBxa0xLZWVpdFNYYzd3
            cnVIYkNjWXowdnhCQmdBWjZjNExDNVJrY1UwClhvdTBDQlp3aEhSOE1PaldvZ0hr
            THdZRnF2bkxRL3Q4WnQyWHluVlJmZmsKLS0tIGozZm8rRmJja2lZTG5WNXVOQVBN
            VjNUTkQrOHZNdkc3MW1BRlgyUkZwT2sK5bmVv0zK1e/TbEwuIc8aTxQ4544hOUrG
            yjozh3Ay76oiGpChVnXPZdd8x9dEc4zCM9ffGT6n24xh9qm9vhWLMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13ae2q6s6f8talcfvvnzm6qzfhcecytr506g9xh6mnjpteecjd98qw9qvq5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6c3RUeFNoOHI5K0xLOFRV
            bEgzZStRWmY2QjlZbEh3RVhRMTFlSDI3dUNvClJkdHhwRXpkS0svTnREYzB3cDJo
            dUZuRnBva0R1aHgyMEYvajl6eTJrMGMKLS0tIEhlb0VRT3lHdVFKaDBGZWRlZjFi
            MGNoTWp3cEE5QmJDYldSWDZpamZXdlkKB505/9P5Pf0vjoHcwIJffWYCeKFlgZct
            6T6p+4WO1qxDo557BXrkiErsDVOOFUSpo4G9MM4gnJOknZIvuW0Ghg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nnza2w8tyapmnwm6gawae43j5nqxctqnqcy8xwe9n8czzcytxfmqd7m7fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrc3h5WDY1S1B2ZHVWNmY2
            VlpVUWd5M3lpV2R5UjdidnU0WGV5ODU2WVhrCktHbiszRSt0UEJJekdaTzgzRVZl
            b2V1RmoyaXEvR1krSzFZdHRCM3lieEkKLS0tIDRyRmJGNkRBdVZ2ZWJLUUtEcUly
            akZwd0ZCRHZTNFB6ZU56dVIxay9GWnMKoJuZDnW6seehx5BKaVNJXAJcR98nLHm2
            VUyNI2rpt7poV/M4cC8+ZNGxSLPXgR3noi/dKgCQHLBv76vsYsORvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-02T22:54:43Z"
    mac: ENC[AES256_GCM,data:pTpgjife/f+QM5v9j0Q+GC/JMxPQ7xKjtUX/Z/lpLqYya5WejQWOebO5XMpbdWpY8NlPTaHUolmrP9+5rG5NsM3tugqdRoJMkmtKevmBx4O2U5utPE/oAZwe0dht+xTOv75cEg+5UwlJf/f0xfSlTNe9qUfxtakwQmAfh8Q2Ip0=,iv:QWnoyZmRzoHs4TR9MAk0ddPDcz8TJD+O22U0FvwCZkc=,tag:R7IxtXmP4ZpUWz9mZyi16Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
