#ENC[AES256_GCM,data:I0pnRdtZgdFJKkpb7PjCTFmjy/d1SDBJhfCzfUxAVBfGsH4FU3cUHD7tOE+VXEAFTehb+Z5pc3YonyLK+0PpIx7h,iv:VPnrx0HfVJhacb+E5OSnECU+g07IyI5qW/9IZem0CEQ=,tag:JaF1qDkZaIpiEHmelwN1rA==,type:comment]
#ENC[AES256_GCM,data:DKZR7OSTSM+3ZiS7q9hT0oQtlgHkNMzkKAwssL/4Y4l5ya3FtqybTb90FJjqzvq8mIbNsw==,iv:aR6lT2jn8Khea0OaWdwqcTsiqPyWJ+P0wB6rR0y4bho=,tag:t7NCorQWKmLnJ3cSppPUDw==,type:comment]
#ENC[AES256_GCM,data:P+9D2FqEKYEEa5sl+qiyUvgwCr16/keu4Uqk3BISvVL4avHJc7iaH54479xen7C0HL5K6NhGHDN/dAHali2VzTYQ,iv:gwO9CadQI90LPCWBvh+aLQgM4dNKYknIf7slKY68mwY=,tag:vunz5eRbQng3otvm5sJk8g==,type:comment]
#ENC[AES256_GCM,data:qc+SiSwV0wlbsPDNOux1haAu76O/E0Ai/lhSsBwCDDh1JOTcplA39n7kxeBuRhRzifG4cWTXl1/KCEBQsOdijvI=,iv:zgnH/NXQvDneDrZn5/K3v4iAlzZ1piWbL2N+v079nA8=,tag:1bbp1RMU63WnsAKPlNbfgQ==,type:comment]
#ENC[AES256_GCM,data:P0aWl+kloQl5larJsIvL7TIjCEi1Y5nYQZcTPlih4vvg5L02cx0Bd9emNpNgxAJKBVCeJ+jUatqiwTbBssevjfw=,iv:6O57HbLdD1HGmqevHtXbs1uwKYXJcwRyQ4A/5dtwF6Y=,tag:KEuvMO6b4SdKE3ddMf6ZNg==,type:comment]
#ENC[AES256_GCM,data:dYYOpjyIHZnfmsrygPReFga4+lxT/76R3VSdZBBsH7zyb4ic/lIgMIICZwnJZxMiuVI0z7CCbBCIB5i9lZ5vrS2g,iv:4SF6gocJtfUTKs2F6HgrqWv/36LNK09RJTuJIsuJ7rQ=,tag:DQryextS07N1c+mw1iwc+g==,type:comment]
#ENC[AES256_GCM,data:/qTMcM5bXjjNY90q8YnJZ7lsnO+MpLQs6ZT1+WIVPgc99nwr,iv:H3bG+rfP0PWokHy8htfnIVZ0swpesdf5B7/xotdw2U4=,tag:L4KB80VpAhfyr7tyaKJOUQ==,type:comment]
#ENC[AES256_GCM,data:LbkaNHDUfXjLwUTd1q3ltGh2Wu2FkVs=,iv:ubUsjhQqLnbpYziUb1oNwb7+1t8bg1qAdietQs1UpBA=,tag:UfAIykrqx6Gl0MYp4otCzg==,type:comment]
git_user:
    name: ENC[AES256_GCM,data:AuK9+Kv/mt0Zqg==,iv:0SV8YVYhUCEgNsjMtxo6WFQLB8gLWSijgNIJ29FFULc=,tag:Avz/moa86f8Dh6LgCxYPYg==,type:str]
    email: ENC[AES256_GCM,data:g8yAQ0STdoDOXHX+cJuPYhK6IJp+KTbWWHjfcqmolx4uPWE=,iv:gSFwhpoD5ouY2+b6VTko+2aqklsid1vwMp++Ug4iec0=,tag:QKflh2KCt7vFfwblypa11g==,type:str]
    #ENC[AES256_GCM,data:mFWDw8zQz0kbc+OgQyKRwWxZvf+7th8aeD1eDmswEKCCaVZgjzK4YUP6pBF+0lQ/iTNs,iv:wvWIYt70PKAJ8uULlTuO6E0jzZl/A21QXj26NGVZsGg=,tag:dJU5u7gIZ0Ej/PFkHJmW+g==,type:comment]
    signing_key: ""
#ENC[AES256_GCM,data:oEd8WDgrZaQvvZGRwEQAWn8a,iv:poViPHQ2omYtD8And4rq7xFXfi35ErJKHRtp9YHDzC4=,tag:snqByL9H5kXRVKeKSikhug==,type:comment]
ssh:
    #ENC[AES256_GCM,data:tAsoIFEYJmBHgcSDS8hSO/1YnIMJ/qHsy1DqVoz+boNxMm/e,iv:f2Th6MbwYXcyfvNysCo15ScopN8rsXBRJ7MFSN4WmIU=,tag:7DXm3s4ybF93oPdu49rcJg==,type:comment]
    generate_key: ENC[AES256_GCM,data:UPnI2w==,iv:9+XJgwydTonDQ24RnIRstQe+ACwvnUnwdvgQ6j4VTw4=,tag:6HFMQWMY9x+C8lGDPZxHsw==,type:bool]
    #ENC[AES256_GCM,data:UxcyG5f4ifN97TX9v/R4XaXkfPAUsg==,iv:dC5aRbNa0ggWswygRJdTAlYg2nsAqCMArPieNmLGbLQ=,tag:Dor5D1IGtifG1fESINLMaQ==,type:comment]
    key_type: ENC[AES256_GCM,data:F6oMgAkqrw==,iv:PRTWvVf3Dt+UrV1PFsRRJNXZCX69ak3cll3fwsw1jac=,tag:QHbUg0k2i9nKft7K1aCh4g==,type:str]
    #ENC[AES256_GCM,data://qyuCoCyQ9S45YtHBtaC3qfJR2DWA==,iv:D6ZdmffP4e/qtHTCVR3KyTaozuvflWgxl+VdYlhwHL0=,tag:wv//gcIlhyHWmCDI+GxaWg==,type:comment]
    key_email: ENC[AES256_GCM,data:u+VDu3uTZDrJ3XrkvWXALHdctg35,iv:Q7tq9zE7zrIKy0LAM0cJX/jZGBKuChMZoNt415s7ctU=,tag:vq1GK4x65K0GDVoE83nWWA==,type:str]
    #ENC[AES256_GCM,data:C4ZYx+TJJcWtOc2TOfiBoSkSq27emdZ5b+K/teiBbxVEQM5goDjPADNo9hBSrXVCUKUIzbKvlTZsfdmv/oZDZg==,iv:F4A+VgaRkMkHobmVQYhIDKSzWGcfDI+ugACr5U4zQvQ=,tag:0A+phYSGXjCSlTJcJe0nEw==,type:comment]
    key_passphrase: ""
#ENC[AES256_GCM,data:mfJpmJYjK28J6bQlErgYGBmL+CMW,iv:kgkTG3wK+2QeZMUH34EOFEBe1SQWI9zY0lwJlGrnto8=,tag:LklFAxtMybawmY9fLdMq5Q==,type:comment]
github:
    #ENC[AES256_GCM,data:AnpJMHR1ogut+U0p48HIUkymIYmm,iv:VdIIlPF6BT8XjxMxi8a1JRLIA7QpE1B0hzW0CLBAZtE=,tag:bnuiznBqTZyqw38stPfAeA==,type:comment]
    username: ENC[AES256_GCM,data:7CoWklKMacB5+w==,iv:ocz0Eho538zjY5XfupRnfglcD+2obhARYERY6KuDR9c=,tag:hzfpZN5r71wHwpCkhmXUpg==,type:str]
    #ENC[AES256_GCM,data:JSakQQvAuNil4Sf6BUtst5qV5f+5lBMEboEuE3S36L2odQKilEB0F0w=,iv:o6jPgDSl2df7m77FWGS1uO0VXbRt5mrmQgNm5L0Qy6Y=,tag:FRllhSjkcGvnvsw/oSq+Tw==,type:comment]
    upload_key: ENC[AES256_GCM,data:GeDgAA==,iv:Xz0JktCqCP0x77XJsIlm3f04YYCeyH5SnekIDIZul84=,tag:cV0egYLsfVMP79FZ2Zme9w==,type:bool]
    #ENC[AES256_GCM,data:RRF9tuPUlFzqifZeWdQ9KPCxwJrAYzh1nwJB2WWOIhQdK7i6RG4W4VagRF+UQS5V6cr/,iv:V6Uo5a57zewJDdyEL09BseZehWGRM3NyB+evmfSE6Uw=,tag:dj2Xo+oHJmuCe8nk2Cc6TA==,type:comment]
    #ENC[AES256_GCM,data:mY7Ril9uSKp0NbsBREqfgnfc8Mri58yEkXucekxKSRMbAfXO,iv:846qgN86hvVdNuCvzXEpdKCnnVqyg6rMo68wLVPtLpI=,tag:ozFoR8FlDNYsmpml5tMWKQ==,type:comment]
    access_token: ENC[AES256_GCM,data:2wPeNTfB/cvJeqvo1Xf86LjM0YFwt5hywlTwDhxBaDf8bny5CPm3SxcZ5tP4NPqQVyOVY/AXX6wsRmtva51bZkXfgdzo1h3Shr7ADL6rcaAtrSNnvhwNnNlQ202e,iv:hCjE8jEdPVqJLQj3ZbQjjJDXpCgKGlaT7lufF7ORIN0=,tag:RNJKjNJgjrRUjvMfL2kYYA==,type:str]
#ENC[AES256_GCM,data:GLsHpBtyE8/6aNlTRXr9,iv:ZD6HATqkOFu2c/Dn46C2YGEhce32NZYNFXz9KqXIT2Q=,tag:FmU0sY0eGRy3Ax2mwY5m8w==,type:comment]
network_mounts:
    - type: ENC[AES256_GCM,data:E2GA,iv:8uZEF25jG7Vj4HbLIU7HFBXSFnHdN8CWNav6yW508SQ=,tag:/fRX+dQEkKV2cNVUX8lE5A==,type:str]
      source: ENC[AES256_GCM,data:zdh37xMdo7mrPEG+Nq0XbEczOnki,iv:sew7FKlph0tsUld7SBEJg9vyL32coPj5yCdsTvmfEcc=,tag:MGpXFzXMx15cyKWwxne+Ew==,type:str]
      target: ENC[AES256_GCM,data:ES6LijbOJvofH8Q=,iv:IuzbmobeTJp6iZu5hYSi0wmpayeSLNsVf3PPK9sYPh8=,tag:w5VA+c+BpfU2b/Lg+43L5A==,type:str]
      options:
        - ENC[AES256_GCM,data:XuVno+cO,iv:9Xhy7MJ31iXcCY5DYJPNBk3qMN7/NwaI7NrJZ3EfA08=,tag:IfnMEvAOb+Qlk8S828plkg==,type:str]
        - ENC[AES256_GCM,data:AkYptysR,iv:h57ybmlq47INLyfqzz6HsGDaXhViLwH+iTrubw4W/pQ=,tag:mmDcssYakQCi0RPEMx4QqQ==,type:str]
        - ENC[AES256_GCM,data:83wrVBY+mQ==,iv:Q7SiYBG4Pbo+yhTkGRq70suHOLV9g+fbaxlUUtI5Qs8=,tag:b5cP2ZWXDHCdfPZb9IH2cQ==,type:str]
        - ENC[AES256_GCM,data:8uvbDg==,iv:cPNsjIVGpbAoRYMTVoY1p/4rQESiwToOdplQv36iVLM=,tag:fmZYbo6qxTKQtesLsmKunA==,type:str]
        - ENC[AES256_GCM,data:lmE7bfZGlPU=,iv:VlcxLKw06slqc4cLQVtY4PNIJ9xxYQBRcwmIoHc5whE=,tag:7awT16WKGF6Vw1nB0TTycw==,type:str]
        - ENC[AES256_GCM,data:diPiyLuukQ==,iv:TMOWYKLFBUHH4GPYeVWMjUxK158eUfi+WQYXWwEhfc4=,tag:r2Li0Ilj3mNXQOpKFIxYSw==,type:str]
        - ENC[AES256_GCM,data:MEem4HY0exnU4Funb6beQqdFzA==,iv:MpPGApb2dbH75HJuHzj5r2PiZDnz4fQ+/BUb/vbCUkw=,tag:8+eFYLcIAxbShlNZPYlQaQ==,type:str]
        - ENC[AES256_GCM,data:eWko/dDHwudcrqOppDAJpfo/F9YdtyathA==,iv:Pht0NPCAO2A7R5OmvFHLqQk7y71ejigFSCTSh12eR8A=,tag:VdX2EZnA002H+Z646eX6iw==,type:str]
        - ENC[AES256_GCM,data:HHc=,iv:86XGg7w4lfEmAvoMl9CGdaGxdEUQxtaxQwpMAUVnRLs=,tag:0qJBU5osGCHRuHIt3dMtig==,type:str]
      dump: ENC[AES256_GCM,data:mQ==,iv:BotgwUJVYQvy5zKykpEaD1T+VWMZbSNrpTuGOl3c30Y=,tag:FBoW8ajvVrvI1EBhnE4QzA==,type:int]
      fsck: ENC[AES256_GCM,data:NQ==,iv:BRo3dn2hlqWQhdFz5KslcntrhTcsUBHfBPWmeEph40k=,tag:CHUqsUuIGAv3lZFmpqBahQ==,type:int]
      permissions:
        mode: ENC[AES256_GCM,data:g7fR,iv:3q5No6EbBgfPGfhDLTZIqlc98OvSYhQWBZKDYhBTGJU=,tag:B2Gjd29aFe/zenvgziqaqA==,type:str]
        owner: ENC[AES256_GCM,data:jd2IIQ==,iv:EOyI1ITAXShTyKFlkvtATDE+sNN9iotZdz+O/1bfRkg=,tag:Pwp/l3stXV0UuZVBF0jPvA==,type:str]
        group: ENC[AES256_GCM,data:MZ9kWWyu,iv:YgQ3W8VSceLNCcJO2CCFO1NLmXKXME0Kjz/SO0pC0wA=,tag:VNDsFK+Mr0V1y6zjeArfzQ==,type:str]
    - type: ENC[AES256_GCM,data:q96x,iv:JNTFP2IcDOWBhnwjoRtpFIztmVpeO3FnMrFtJB3fzXQ=,tag:GJLFTC3iimecfyoPaTWduw==,type:str]
      source: ENC[AES256_GCM,data:gL+soIWuPdQcogWX/T+Pglx/Lu6zaA==,iv:5m0zn4zMSeZkBIxYbx6RhAXKtXVV7syHHlHFENzY+/M=,tag:V3uHFRkwcIMqfQ65TxBsgQ==,type:str]
      target: ENC[AES256_GCM,data:po8SUv+X70lCl39B,iv:dn4c6Dls7gFt8IoKvpLwu1gFQnBZvx9SvRh1Eu9S0YQ=,tag:ETzo9TgAFD3dQN18oNPtXQ==,type:str]
      options:
        - ENC[AES256_GCM,data:frnqhlb2,iv:kBZ3fKEsRTEp0OlE/unt+Jue9KbpQWQFkn2vlqzPN44=,tag:Yz9PVgGTt08ju99YFL8oeQ==,type:str]
        - ENC[AES256_GCM,data:GfpCYT31,iv:Pq9in6aa5ahoMn1ngHAk38kk2o3ZiRePUpBDTpPDOOA=,tag:D7PHx93RHsv9uVWCgztigA==,type:str]
        - ENC[AES256_GCM,data:iFsKoqON+A==,iv:nTSQtnXjnFcuuSBNXIwLKPFeMqsJ4qzKYa+wt2Jl9H8=,tag:MzDAKSxqfI2fqYmn67udEA==,type:str]
        - ENC[AES256_GCM,data:vY7RUg==,iv:5r7Qg5Bz+nH5YQSlNpKMahIxThTnKt7paJ07b9Y9gKc=,tag:eRYFLiQpgS9eilTegRpY+w==,type:str]
        - ENC[AES256_GCM,data:Qp4m5Nymhks=,iv:5nMgv1lkpnKWJHPNh21B0/JOnBDparKuI/dDmk3cO6I=,tag:HsO4bkqYxXp+UDGW+tZr+g==,type:str]
        - ENC[AES256_GCM,data:Xp5gg0lIEA==,iv:QSHcvShtMGibOX6ws+glQKIlZ5fgF2z5PlDgpbIpn5E=,tag:4kiE+7WfO3MobVygRlar6w==,type:str]
        - ENC[AES256_GCM,data:qz1TsuiVJgPwzYrpNXcQgJTPhw==,iv:biVSzpmX1I/EWmNImdXDJuWLvRA3PQF6Xe/pSH1UWXg=,tag:b+tYLNHgQm2cn+RuUB7XOQ==,type:str]
        - ENC[AES256_GCM,data:7wndKCaDGz/lYx6Xb464q2n2uuKn8kQCpg==,iv:BoByL1F+/jkpm5Uzo/JStTXZO3A9of6b2FX7Nmls3IQ=,tag:qfoFOyqG+jhXoZTBsPdsbw==,type:str]
        - ENC[AES256_GCM,data:RbY=,iv:QrZw30CZEpUTL8k9s2te1A3x0rfeQN8rWuvyOC1+hFY=,tag:o+EODuB3Vay+E48DL137Lw==,type:str]
      dump: ENC[AES256_GCM,data:4A==,iv:JYjwgcdmAU0G9DnyGNW3fzfrW+RsOwIG4E7gZbyn2PA=,tag:fwwZ1YCHQYrYLOL0LpySYw==,type:int]
      fsck: ENC[AES256_GCM,data:9A==,iv:6B+S1YfvCbmRYITyxSR15RWaISMwvnhIrFKywJS9yyM=,tag:LtSqvdf9c1qXg+qmrlMtDg==,type:int]
      permissions:
        mode: ENC[AES256_GCM,data:VNVe,iv:aZz77xoRYl2ho9/jjvhPrRfpN310WslOqscco1BSdHI=,tag:jmM+GdM4kUyvU9VeienWuw==,type:str]
        owner: ENC[AES256_GCM,data:feUfqw==,iv:W0xKTZYQzdbnoTui2wQp7bYSZxJU6qq8RIUTPfATygk=,tag:Bs8M94mR9q7uPg8kGZwWOQ==,type:str]
        group: ENC[AES256_GCM,data:D9dchvHV,iv:Q0qT9euL+yA7hqe09kQ9VQ75/OdWtR9AxKMzmTt50FQ=,tag:EQIJFSGyuXVt1RtA9qKTJw==,type:str]
    - type: ENC[AES256_GCM,data:P1pS,iv:jlGDh6puDhy+j2fEsxoMj/mT9Uxdh5qjWCfSD2TQy34=,tag:K2aCZrASeyGMneOX/6pHgA==,type:str]
      source: ENC[AES256_GCM,data:zqQzU8oOQts5AH0sypQllHc=,iv:uqksDI8BfQok7/FTA7X+8dHWvD9WPokPzW9sJEy8a7s=,tag:mZtltvMtdmOeQKr4no3Fzg==,type:str]
      target: ENC[AES256_GCM,data:DQ9qPtzAZzi2WEHZrjzVCLKO,iv:gdNCcRBMvcK4Q/7Dc0L+MaWKdwyIODDJ+hOAaq3G4g4=,tag:6p5faYzIkKQFF3hxoG7lUw==,type:str]
      options:
        - ENC[AES256_GCM,data:pBbPnoii,iv:zmbn/G47RP8kV3N+oY4aDlO8w9PBtV1TMJwD6/mx3do=,tag:pDGIvt0DQsLMqOZPcn2QRw==,type:str]
        - ENC[AES256_GCM,data:kqVGyiNT,iv:RvzweagtkdfLPBvkQZtUp1W00vG1jOSjUqf834q7vAk=,tag:J6UjrGp0VH30ZuPde54Mpw==,type:str]
        - ENC[AES256_GCM,data:tE0hiNIBkQ==,iv:0MNodrMgMxWylM0sGO93q3y/LQ6RlwUj0MovOatpV48=,tag:eiaGgp4jGIW1o0NZTViI3Q==,type:str]
        - ENC[AES256_GCM,data:KhlltA==,iv:YAvi25dQMVfmlwmgh58nl1V2fj+QWr40+2fTPSp2jR8=,tag:n7/1cL5QwTuWKSe/wMMMfg==,type:str]
        - ENC[AES256_GCM,data:F2Yu2OKzb0w=,iv:RSIp7mdTQmsyjePGndFxyIsgnysrbL2EuBpB92Q2uiw=,tag:XVPNYlHSnoMYVL3v6i/OMw==,type:str]
        - ENC[AES256_GCM,data:pwOinX6K+Q==,iv:x2LF6JEyGqs5CytMYsV9Z+dSyQfT+Y4jXhbOc1LFhZ0=,tag:8MSReYGxLwTmgFMb4zshDw==,type:str]
        - ENC[AES256_GCM,data:XZ1fBJ72H5IzPwxXn8ttXX3h5g==,iv:X9UXOUibG0zyGVbKh3ha3dmnx0D1/nTKpvhRHWUKWsw=,tag:lc17c5UTU4tiMAl/aQj5Fg==,type:str]
        - ENC[AES256_GCM,data:HQs5y+RgWh2lVUr2gD4GPSoOZOmAM2916w==,iv:cBhX62X/mGZpydp6M2E4Ga8SnIyux8q/ecRcxTdb2k8=,tag:GvxoeuHOJE07YQE+rgFniQ==,type:str]
        - ENC[AES256_GCM,data:ytk=,iv:OD7r0CZQKGzL3PHyvLbqmzMKbsQid3XZNtCRtIemRBo=,tag:OCYq33cPeqJoTnafYaynGg==,type:str]
      dump: ENC[AES256_GCM,data:sw==,iv:Q/9LrqLxA+jjT2ZCEM1P9vuThRNBh3GygOyYvQ/cujo=,tag:dXTnp55go+1wIKcg83IGoA==,type:int]
      fsck: ENC[AES256_GCM,data:nw==,iv:Oso0p2QZc5xLgaK+0UPTeUzdTFahCIQk9F/hrI0JejA=,tag:5LZ8cNTHliGUL7PAWAyj/Q==,type:int]
      permissions:
        mode: ENC[AES256_GCM,data:5aTQ,iv:mNfw5Hr/TKj4Z5CC+l7mcHsWiHrXLX2/TU0EI+p+nrM=,tag:41yCpJFi/xUuK0Y0BHEI2A==,type:str]
        owner: ENC[AES256_GCM,data:wa096Q==,iv:2jWKaLm0ls54iIUNUAXwzaT6QTd4bPVG3MGT11MJVt8=,tag:hc4vdz7KfIPKvhVezqR7nQ==,type:str]
        group: ENC[AES256_GCM,data:vxMiqNUi,iv:ba53M7bmHf2IH8s4lKHYKt6QMUAunQD/OG6sTipWxcc=,tag:HWvqQrIdRw2jmbd1gRsUFA==,type:str]
    - type: ENC[AES256_GCM,data:yFpW,iv:lO+uZomTGSLa4+YRJZf35NHrOz5lLOpLQlMDH5+E3zY=,tag:P1a+F8QScgA/HZH5wgX5Gw==,type:str]
      source: ENC[AES256_GCM,data:KJu0ELuMF9GTDoVrihpuWZgp,iv:/Eg5tplPg/IX7lvvDtBcCfOwEeBGW/mXT1mNNG55oiI=,tag:auXH2BLYhrtu8+xO2yUrEg==,type:str]
      target: ENC[AES256_GCM,data:WUzi/ClJp2lQXxFirO3zWgx0Tg==,iv:HIYagaNzmpC3G5nB7303Gv4mCWuCkFCB3EjBikJUMqI=,tag:fI0OAkOU40d4czrIKRWNUQ==,type:str]
      options:
        - ENC[AES256_GCM,data:5VtDS52g,iv:iwCa4YsKohZKOW/+4yqLeZeqNqfstAQ0WNjHqGyFY80=,tag:j5E8G/hdnMhEIBiM9S1T+Q==,type:str]
        - ENC[AES256_GCM,data:G/Z9I+OM,iv:fKxaVOSM61zSgVBmqZ6I8LfRPKxIUtqjHnE3imehWmE=,tag:6OW1JONXpvwPUusOfi3/NA==,type:str]
        - ENC[AES256_GCM,data:Rjj33/mzHQ==,iv:vE/v4enhepsfOj63Rhle5LxQOdJl0xZ3N610gy6TIwA=,tag:Iy2FcTS/WRSZqlyMpM5+IQ==,type:str]
        - ENC[AES256_GCM,data:0Re4EQ==,iv:mBF/TmA3LI26eLkQeb33XxqcM6I5IIwwOiIGQQBr6Vs=,tag:nx3z1ORaG67FhkP4Mp9ulw==,type:str]
        - ENC[AES256_GCM,data:V7zgfKqHYjo=,iv:cPqE8VCFz7dILSJcmuJU5iuLnBnDzgMDK3uoqQ0HQQo=,tag:ZUunAER9Io1t1iCK2B8o4A==,type:str]
        - ENC[AES256_GCM,data:aXpDOAdwOQ==,iv:Kcliy4hBUp8p3BEbYt5+0oaEaiGoc2VjD32yVq/SLx4=,tag:tzZHm8laz1zIeVhyWmEvpA==,type:str]
        - ENC[AES256_GCM,data:HH6epUwH378i7ShnPwW7iewDJw==,iv:VYnWuQYFuvtZG/8xUaiVqZOlZ2E4aoFLhtw5HSiNz6M=,tag:xm1VBvdThcrIcDuoIxugVA==,type:str]
        - ENC[AES256_GCM,data:iLxGbHCksfrln5c+syEYA42xGN8YiNpxIg==,iv:tTzfOFDbp3NDU+8kr7qp9+y8wDm48XX9TJ5JgeafHMw=,tag:hPpSO1ssuk+tObGH2Bbr/A==,type:str]
        - ENC[AES256_GCM,data:Mlk=,iv:dJe8GlIOo2PvTTFLToj1LaLu7ZSoFW+/TvvbXmQ3aH4=,tag:k+WOnUTKbaRBXPqdhpCmTw==,type:str]
      dump: ENC[AES256_GCM,data:rw==,iv:1Skp7LwSoVmjrXOa3e8VjijZ06IhUN7UMsp2B9mYp5k=,tag:Ujy37xUDp77N/GdoFx8Jhw==,type:int]
      fsck: ENC[AES256_GCM,data:6Q==,iv:6MzU6KIY+6988H62jW8hOm4p+GJ7GGYEgTSV7Q3JiB8=,tag:8hyL8MvobiBlI5Y/YJEwlQ==,type:int]
      permissions:
        mode: ENC[AES256_GCM,data:mECo,iv:Qo/Kpy5y5bIJLhoV0OP12hT1kM9cwZOE3agy7ZfxXjA=,tag:tF4mnpNbMMb2Yxnuhvl8VQ==,type:str]
        owner: ENC[AES256_GCM,data:dl1J1w==,iv:qmnC77QCBK/u3OuzBnsVAXEvmsExCMdvlnp6VrAnK6g=,tag:2ZsVNJ2w4T4czIzRbVpn/w==,type:str]
        group: ENC[AES256_GCM,data:tJCI/gCQ,iv:JIt44jINbVR+dh7uFfQMAvO1kwoWjNSR9Qo57COpymY=,tag:N/YFWIYD1cUIpUWaokMmow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age172unqujv5uv885spfc8gk7ztru9y2lc3jgr20s3gpt9lzhtt8gusgzusdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFRmhJcDVOQmk0RDEzM0J5
            a21iVUNma2plYVZEUTJpM2RTQ21qQVJJQkZJClAzblRsUXdMaFhMa2c1blRFZHVv
            THJnTmVFVnRWRTlWaEphM0lPRUk4ZUEKLS0tIFJxa3c2RXJNYkY5QXVjNS9XVWJM
            eHhoMnJ2QzMvbjYrdmJJczVrOWVhSW8KYUc3YEg4aMoyjTi7KxsL/1jbtyZxEujG
            9mEELF9wGSbeVaD4QoDzd5Wl70JTQted65Jm5IlMItg3ngLwQiGDVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-11T21:17:16Z"
    mac: ENC[AES256_GCM,data:0Sw7FNovqRSsI3OIIUuotzM0FcEMLeopgI6Y0FfcYoG530d6oAnON1D0sbsml3OYsBdIg+VThykGq5Ri1fudTF/D1lyVkGjJ2CuuZTGuH1WDLikRXhMOOVvQ/LyFp3CxoauIxkRpu2s4TmG0ld3p20x1CVPljdE72m+j9bASJto=,iv:32KiR0wdH29VmhC/ZRv7HfyO+RAxFGyYGBfnDOJ8YWI=,tag:GVypuwpH6VDRlAljhWsdNA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
