#ENC[AES256_GCM,data:FSeUQ7gAsMn6PFXhzaEJJeN4ckHil57RQ5C3Gv9Mq8izuD80dVLv0WKO7rL/udQxbwSuDpwtK5bn7jgJcLdqExi9,iv:aqVohpAwrzHnBpXJ97Kx7IsJPS3ln9q5JyBAcdI2+aw=,tag:OBphdzXV9/Dgv0jd5SDePA==,type:comment]
#ENC[AES256_GCM,data:HT/DB8rtUeLno8KVGY8E9Knw/+ebAh/KDrRVHF6b9Oet2EK/Tn6sHIPjIcqyqq8jNk1F6A==,iv:6FRo7NBq4+3NsWE6hrbxWxBYXjO6BOCr/FZGrQ9WNbM=,tag:mQrlODtLxVqdsPpiVF5sLQ==,type:comment]
#ENC[AES256_GCM,data:rgg6UinpZ5xHoCH1DUs44LjIF3DlofMjdoPTqSsR5yF02YTDC+lio/Hb3aTMNyq2U9Q4qUT36yYLKDjvmmyC3b4Z,iv:cXXmQ+oshz/yzjSZgphB53X5v/QkpKUNDg82hIURh/I=,tag:5uqp2tjecWLoKChAs8geng==,type:comment]
#ENC[AES256_GCM,data:SIdJnQr00Mr3oCIqJ/3igqopj9qhiKYn+Nmy5WcKt1Kk/fM1oTtWK2AWviD2pJwW+Mh0rdZW0cQbZWeRWIsPctg=,iv:ugCmOM3UkZbvOJUebmAMaM2+FLmuJbR86QnRKc8mwpk=,tag:TShht2+v48fnVRxkTdnsrA==,type:comment]
#ENC[AES256_GCM,data:MgPGUiMifoTqj2ZmtGDxYrLByz7wakgts+nnkntkQqZWxVyT/J1uTolVVoqPb3UqqrCPL6/nBsWvAyaqwPapZe0=,iv:HEBPcyKOqdrzaAgzgVhZeDUln6nS6h5tKnZPlejddCI=,tag:p8KJEJ3seUiFzusrp5P8dw==,type:comment]
#ENC[AES256_GCM,data:QoIqgzO7jtg18YqxVIr2e41ntoa3YohduND6pVDLdPlkWFNoCE9FLn3mPIwbexQOkM2Ly1EMhcouvSt4zvwndE56,iv:6JkOkuYeVFQMdyOP8hIQ06R94jw1sGtfaAWI5r2WVMY=,tag:v7yV3TqMRtFOd9OnmOYZyA==,type:comment]
#ENC[AES256_GCM,data:uSUvKSqVkPvA3QEm4N7yuw86AFBuModVWbaCDHlNb0nYTsUx,iv:hJ/p1Ej62J4IOaNrLQxppr5Fa1n8mdAm+p+S+UGQwRQ=,tag:yqNQFY4EK1Q4kp5EYcrkSA==,type:comment]
#ENC[AES256_GCM,data:It0laIX+3WKQflp5GqX21YcSfc1q9S0=,iv:mn+OF6THL3sjMEMmT4W/zHz0lkX3iTzNco/Ot0FGxkE=,tag:8u7nMy7y8Fqvn4fZroAxKQ==,type:comment]
git_user:
    name: ENC[AES256_GCM,data:ygoOvxnhcVQRcw==,iv:lNEcfpCJvf7cho5HB7kkuwF+DN/xNTgTR6FC+WyfrHM=,tag:B0QI/twGCN+dYmJsrw3TUg==,type:str]
    email: ENC[AES256_GCM,data:29/JkoBfoYlUqUvxG3lqjaZ6gY+1hQjLEmNaO17stpVFI5A=,iv:s979ZibpWR0cbtIP6Df8NseqZIlivgoNdkuUPU2btv0=,tag:x1MgGFNz6lEqzv2kxy46rA==,type:str]
    #ENC[AES256_GCM,data:QK4LxrvN7thLz7UO1dcOO4COEFx0A41BnsxP3dyJnm7/rImr7KsVZ0YObAKRwuTi4dbn,iv:by0L+hgOn9eamJCekFCGHZDEcf0lw3e0Psvz7CXMvyY=,tag:HIL1VMW0Sgb4PegWnY4rjQ==,type:comment]
    signing_key: ""
#ENC[AES256_GCM,data:4dyXmbolrOYp7vMjXadiV8d3,iv:C/I3AMDoWZIHwbfXZ+D6Gvi37TyQXkMYP6fAlAwke64=,tag:3u2hEOYhbfrFP3qgNret7w==,type:comment]
ssh:
    #ENC[AES256_GCM,data:e50w6UtXsg5i5vHmm1ny6xNZNGs9VYB2ChdFAyODogSSpSC3,iv:hQxP0TFoQxoA0O2fn0yrVn2WyjpGx+yOQJvni6+o+Vs=,tag:TrT50FM3HwhNmnBPmFU+Tg==,type:comment]
    generate_key: ENC[AES256_GCM,data:buzp+Q==,iv:U6cxW72cxVhtZmdal1Z+JxtzP0djia+bdVOIxCh5vnE=,tag:FScvL66T3zRkTkN9ToFZOg==,type:bool]
    #ENC[AES256_GCM,data:GSIanG/h7CwsdPfz0JlpC8sGi1xlwA==,iv:PgTrHh4RrEAFaJCBQ/YSmYJ3dhMo/uFkf0drE5LKRbQ=,tag:FGxp5RD9ZIn8kD1x+HjMeg==,type:comment]
    key_type: ENC[AES256_GCM,data:Q7keDgl/Iw==,iv:CgsSfpW4pbSjo2G+W3AzNoWPW1DxMOabyVKpoIkaEVQ=,tag:jpEIXU7IOY/nBLWlq0U5Sg==,type:str]
    #ENC[AES256_GCM,data:c0rNvHrINR7knijU4Rzb2yvrYdaz+Q==,iv:jm1fSlMKGTuJW8p/T4LAD1TVC+jmPcLAGT8dpCyG1tA=,tag:+H6tjBUWtsIBQxvnBv3I6g==,type:comment]
    key_email: ENC[AES256_GCM,data:1UnSk6Kq6uFYnZgBf6sWkO32jiX/,iv:dutcbelgOvLlYQ0zmdUiAK8MiCj6N7fC+qJn3ukt98Y=,tag:oEmfC2nH0UfBeDsvwsIwoQ==,type:str]
    #ENC[AES256_GCM,data:owz/1Ww9TRHrfpUtHC04W/x8Zm2hMYnojAJ6zPTZUK3mk365t64am7RrM8rpA+ecKh/7n62Iha8c6zrpqAfKAA==,iv:0ZxN+nBRGHnrd4Bm/G8ssGQ+cfjH1tiEwfUBZ8aentU=,tag:xbZEBGXGS9R3TJy+/+Wa9Q==,type:comment]
    key_passphrase: ""
#ENC[AES256_GCM,data:N6wmy+hjWeoqptmir/m+Fy/af7tM,iv:7TYggI7e8iOtZj+fqJTwOS+UGXI5VoWFUNAc6bTmx2Q=,tag:GJEBna2VY3tcOmul70Z5kw==,type:comment]
github:
    #ENC[AES256_GCM,data:ujrtLMVlZCHeMb7IVR8VhWTGWbCr,iv:jpgbgQjUaAXO3zObh/ktTaylkq9D1yVdYoRtg3aDLaM=,tag:vWIoeFoBkJ0MBLGnPYZ4SA==,type:comment]
    username: ENC[AES256_GCM,data:2cnhGznLioWHOA==,iv:Qo5EyOb5BuEhGqDDhh8e/84eq1bHczdU2dXLCPuMNp0=,tag:wrXffO6YKDPktDEouHFdog==,type:str]
    #ENC[AES256_GCM,data:mB4cQOuUfSOmleIutsHWNSPNeBszgsRehGye2fowhtczJqaVE6WQ4Vk=,iv:7iZo7DaIhl7kfJP0zdmS7xV1Ec7PP+mA+X/CmSi02Ok=,tag:Q5i/NS3OzN84EGaBsrWKCg==,type:comment]
    upload_key: ENC[AES256_GCM,data:9Bxtjw==,iv:aJ3YCquFUVVCcEviVkbmTychdKP1iBrxWjO8OE9MbI0=,tag:FKQ3Q+p17HBQd3k2eQxjVA==,type:bool]
    #ENC[AES256_GCM,data:0IIkV4bMG32FeejtWiR7RHVJ9Vr1KDFcDQOUowN3iokEpYeV+ba0nGJ2nESw+uSu+tbP,iv:ZblwAX0PUnrdKKSx2w155U/nvH89hAbBH9ikSJ+b9Qs=,tag:qVjNdShICzZPP6spNUJS1w==,type:comment]
    #ENC[AES256_GCM,data:ZatRcQzlsZQwLFhgAnpHvQM9Q16yitiNDj8K9Y/ExIi0OvIu,iv:pLNwjIorlotv90yjJNkx0PkO80mqS6mkjGAhJSUZjVE=,tag:IN39o+Fp8zA+HzTDP3BJfA==,type:comment]
    access_token: ENC[AES256_GCM,data:Cw7DjbZdNNUBoZz9cMEnBwelPJ5yLiAPNjurOGeU29TqhzPMi1YqKS0MazFQTU29jIJg6yPfh/DqfkC5jYuJ3QfdTuSaFCtCj3LQQ4U/hFJU/m21LiJLaHgbq7kt,iv:VGc6IC+QfoYve/DgITMrKHNq2QpKCMSkzEyvUcMerIw=,tag:leaVyfzCMnQuSvaLAcfeUA==,type:str]
    docker_repo:
        #ENC[AES256_GCM,data:bRGUu+qpYpz6cv+SQH6JKkuhz8w5k2AhVHCvkPlKoOv67z3Y+vgcN0ofMQoyUrgLK1ktD6gMn4qWCYZE6S952OyWpKDsqA==,iv:4Hw0ByhgnP0irB8fh22StPwgsYtHno85hXhATMx1tag=,tag:i3ZY4IySnlFj4WwSqQpCMQ==,type:comment]
        url: ENC[AES256_GCM,data:BraSfHHOnuI+7CaNSmwAAM0WriNvchURoL99c7oEKo3vs9b1sXoxu4Z7H8Brrg==,iv:dOirnO75v3ML2YccW8DOKtMrDebZzRr916V9wBXmfd8=,tag:ToNCBB51RxDNByQ8273V1Q==,type:str]
        #ENC[AES256_GCM,data:yqqIIRZStrZ83lSHvEWPcFejosnxgU0eNtfCExDNda39ywBG4BM05fxpYhjsZAtZ/Q==,iv:3m3HdKA+zVEn9OuNrjMSjEV+2vqj63Hf7PJ+bK1i0cc=,tag:q57lX3P3yMaCA8u+wLobgQ==,type:comment]
        branch: ENC[AES256_GCM,data:Vg+zQg==,iv:mxED9DwJ6A1cfmBCn79K1W0YJaVkbtveQSsKorDQd+c=,tag:BMOJ/uVRhI7ze4Jd9WP2kw==,type:str]
        #ENC[AES256_GCM,data:WIWaoRFLPI63HesFd3Or/qTyBpXIrISTTO+ntt/eg/6xS2BX8M8IDsjFERK9eMUbgsXXQQ==,iv:/HA9U+tflPKcZf169EnYEgCVfY3EV2iBd53ysWKyeiU=,tag:RWy1h5XSqV7ELk1Gwg7Tjg==,type:comment]
        #ENC[AES256_GCM,data:RisQFfWRtf0AppsfZP/4KnENQwBKTwj3NM37w+LF7Jh9KgAJJWYXcZeRSjOeQUrFc2W2+dSRMUdCKA==,iv:s/d8N0cVXA5BZ0OxFgeRqa8Hjy+6K65c6s0mTbEeVeI=,tag:jtWxpM03KUt+kOYQm9A4Eg==,type:comment]
        directory: ENC[AES256_GCM,data:uXs7+khUELWDj7Eq0Q==,iv:KmoPu1y5YqYIz+iLOh9/ukMOCecwtyw3S+TvShdUBvo=,tag:o0RVc5zl3oaNo8TJ895oxA==,type:str]
        #ENC[AES256_GCM,data:brvPQckDUUzGmo2YzE6Fdb/JR+2ta7S+cjZIGwvTAODSkHwyuVhP5M2YkK6I0NCuvV0iGIS6FiJUEdzF48DSgIOA32I=,iv:D51LahPgLO+noXXOpYNNKwOU20iAMGGb5mC/njVwI7Q=,tag:m+eEtINnzUd0s/Dr+dCulA==,type:comment]
        auto_update: ENC[AES256_GCM,data:vsgnKg==,iv:JvojL+M+5g44bAlSo7dWO+/AsSy/YupZ2c72+xLHtLI=,tag:9FSaarKIsELsWLkVvYE61A==,type:bool]
#ENC[AES256_GCM,data:uzisKp4SQ6lgn8TvTz5J,iv:OgsiC8YJw6hrRsROGYQcvANsvh8PkKhkhUYUVqmjfV0=,tag:8Txns2VEYDGkOdJ/VZr5rg==,type:comment]
network_mounts:
    - type: ENC[AES256_GCM,data:kZTE,iv:XatffOU+vlGE3J9LJZk4o4kG0+NzvO3H/Uwss8wbr1Y=,tag:juicNu9eKbEf8xd6Cdl3ow==,type:str]
      source: ENC[AES256_GCM,data:K4U3IiJIIctXmE6K669WrpceM6R/,iv:EvP5VXJ/g9mcf6cu8dhtCqRDQHvnhsGgMDMRvp5/83g=,tag:MF//9YODlhDgR8fzRlNLQQ==,type:str]
      target: ENC[AES256_GCM,data:nvQPdWrn8vzGYOc=,iv:aFPObAldW6CWrJ2iza6d342G18jiKFoHv1VMtuXTw2k=,tag:o/CpcywZum26BKRpZiI2/g==,type:str]
      options:
        - ENC[AES256_GCM,data:sxzyiKfe,iv:l6GNNKKNnsJYFlAcM0PqhCTGr2UjZQl8Y/I2LF8wV+M=,tag:8IoeRiJUTH8/JnE/wbJJog==,type:str]
        - ENC[AES256_GCM,data:MKTFmKor,iv:WB4qiGEjYrKrTvNuLdilx/2qMDGeoP1tvwp9gWMa/OE=,tag:FyWeSsmp082qwb9RiZW4vg==,type:str]
        - ENC[AES256_GCM,data:xvlMmsKwZg==,iv:4FoJIlwFROwtdwqr7ymHmhhrdKbP1a9Pl8ZO/43rV9M=,tag:c3O6SHK1bPqWTYTfvALpdg==,type:str]
        - ENC[AES256_GCM,data:vZHXDw==,iv:4E+UKMDvDqPAX581niHymS9RCLlpAwDDGYYEeWaxEaE=,tag:EZMiP9dQ26msMYsrG74scw==,type:str]
        - ENC[AES256_GCM,data:kc+M0nDlIJ4=,iv:wX0XWLl3QwmIj97S9VLQSQerxyZCBIXCX3opvb++ssw=,tag:9rGkFqNIBrHzb4oJONW7nQ==,type:str]
        - ENC[AES256_GCM,data:vyHFgSGSGg==,iv:DQ9LiSIMDgLL2DziErduORROtU/NGeP8MelMTDzdomw=,tag:J1hSXFpDi5m+Q1MqHq4jOQ==,type:str]
        - ENC[AES256_GCM,data:Mo/mkpkOXXyqN4+sBByF4y9NFg==,iv:7H/AOnsycCdJuLgu2SehBH13x40baEuQn/GqGHUjb2E=,tag:f/FmtB3pLrXGbUkQWNWYCQ==,type:str]
        - ENC[AES256_GCM,data:dwh1toXjDH69J+k7+iyWPheFnS5F6eFhQQ==,iv:wftWMyP0xP3/ZfQBPVZL7d+DHcMrdvC9sZuus2++7sw=,tag:7i2+r3ijD6QPcoLLTTJq+w==,type:str]
        - ENC[AES256_GCM,data:pgs=,iv:fFIWWw/zrgQV0s5tnyi6iHLJI5fgBajPsUAuh0sydqs=,tag:rkwYKj4VaqFYd/6H66hFtw==,type:str]
      dump: ENC[AES256_GCM,data:RA==,iv:xwVa7nK2n7gvjRken+5wEr6uVlQvVr2Wzl82rTfc8eQ=,tag:+FIniqxkRT7Vmu0R13Ex4g==,type:int]
      fsck: ENC[AES256_GCM,data:vw==,iv:0lah+UxRMIKrSZIpz9HDwpGXD7g1aROcbEtoq1PCvHQ=,tag:KNCUbkWmDpWXa7at2ftC0g==,type:int]
      permissions:
        mode: ENC[AES256_GCM,data:jVRt,iv:tRtBjQkC/HsOTwHK5S/ONaAHgoba+8O/Z4XWl0Fbmng=,tag:+/78zvzSNsGJcV9qyOnlRA==,type:str]
        owner: ENC[AES256_GCM,data:pX+EzA==,iv:LkpICIxKuyMWTPVcW52fyRPpirDHAMLXJTDnJEDZzjI=,tag:z6LGJ6yF5fSPOl/oTYS2uw==,type:str]
        group: ENC[AES256_GCM,data:n6VC3VZ4,iv:ZUWt5NVTnoOukD7OOiv6Cbco4en8ytRkV/BfN3ZdPIk=,tag:UB7Onv3+HESUKYlzaJijUg==,type:str]
    - type: ENC[AES256_GCM,data:gbd2,iv:CzLzOqAbUoC6E79GCewnlcDrh49ZAKQ0e42K39mOFSM=,tag:K5ce7/Ychjf0MM7Ye5kgyg==,type:str]
      source: ENC[AES256_GCM,data:Z9DEIABTemQ4ThyaPD/I9bAgI4MFLQ==,iv:1TGjxU2xIPYOYQSXWtc/lS56yLXKUEJys1ruY/DPMhE=,tag:mmIzVnRTGP3a9U/bIVMYhg==,type:str]
      target: ENC[AES256_GCM,data:5m+Gau+AFknvXowS,iv:2AAw7hMkksp7yNch8O4FI8Zs0/aI1j7Z+wf2F3QwZgs=,tag:geLVomCfT9K00CdBbJ1y+A==,type:str]
      options:
        - ENC[AES256_GCM,data:iVs5FoIc,iv:dTCPDxEFrPwxYZNCxB70GWF3pAL7nQj88Y0vVjUn6Qo=,tag:EcuyeqPrWTymLYLnFKRpeQ==,type:str]
        - ENC[AES256_GCM,data:hux40WiT,iv:pNJI2iRvoLoTk9JLyhZNU1tC7nsexInfdAUbBssD7wg=,tag:6fdfj4nZ6gedOWRnH3iSbA==,type:str]
        - ENC[AES256_GCM,data:uo4pFN8zRA==,iv:8VgkvV6W9+TOkwrx7OYjymROk/GTeZ/kzM8Pxmzmnms=,tag:/tuZ+oS4XKZoI9KbXtyYKg==,type:str]
        - ENC[AES256_GCM,data:gGweCw==,iv:uLtoaf1gXTcZjsaufXAgZgOcVvKCRSKN9HFZYehXubA=,tag:3jto0QG7HoRfSf8lt2mKRw==,type:str]
        - ENC[AES256_GCM,data:lWxsSQd4Q4A=,iv:0oDcI4FSs8Ffz22tPhXr/ISD0WTkp391XpQ6X06Fvb8=,tag:r80Fnv46EedvLBGoMlCwhQ==,type:str]
        - ENC[AES256_GCM,data:z7ei49Ziyg==,iv:TqN1z7CcYKBjUp9gdlWychrxAP04diB4GIPTkdDr2eg=,tag:VHH/hNAMe/nBJSnS9Bwp4Q==,type:str]
        - ENC[AES256_GCM,data:90hEpSMEbQ1FQFVIsDJO+03gnQ==,iv:CxB8TW9D6uIofD/nW5AMWKkKz1tgVQE5L+Hi+LpAwoE=,tag:+OQKmenSMYvfFB9HYsvCFg==,type:str]
        - ENC[AES256_GCM,data:a/M1bALcIKVDcpSRnp8yOTFLAOpOMhhhhw==,iv:QILWb2MBPOde6kmbqzhnC/YGt0j6WpKiWyQUR9AW7RY=,tag:CVzHWAwjnNR3T4xWz6GLPQ==,type:str]
        - ENC[AES256_GCM,data:sPE=,iv:Kt/f+jHGXwQl1HTxd2zqmslFJ6xfGDKQuHdCtwis8QQ=,tag:czuV4S67CBGw8aU/Sx4ylA==,type:str]
      dump: ENC[AES256_GCM,data:pQ==,iv:/Hy5pEG3nA57fckuOS+U9KhlaGXcWAuJX/wP3Lehdj0=,tag:/jM+u+uiCgKKPuFJiRJsIQ==,type:int]
      fsck: ENC[AES256_GCM,data:JQ==,iv:fYQdp5fm6tB5kbgBoCjYseQw9uZWmxGE+fGN/OQKHk8=,tag:7gRNTyLbrwPu9s2OZUy7gA==,type:int]
      permissions:
        mode: ENC[AES256_GCM,data:siQi,iv:z/WrTWiTQ4EYIUfRyIdlJm0TKzvJLyyza52KABjwU0M=,tag:pEzaZCCFvIy7xMaVQseQuQ==,type:str]
        owner: ENC[AES256_GCM,data:ZVRFhg==,iv:uh5k4JSNymXRfcSemF9gc86Hf974LdzOpqay7aLF2zU=,tag:HbTJgETBJg1D7blRbp74Iw==,type:str]
        group: ENC[AES256_GCM,data:mYUdMvgV,iv:btKZVWv+YfK3fgMG68Xbmfi6nbhW3ylbdvEpRkVmzx0=,tag:nq/9ca/BYqVFFmzHtk+oew==,type:str]
    - type: ENC[AES256_GCM,data:8Rjb,iv:d8sogOrLkt3xYO6mKCGS3hIHpPw/vUhxvKicjv31I+E=,tag:9sIdXPj2uc8aUdEYYQxZQw==,type:str]
      source: ENC[AES256_GCM,data:IMzFtRm442M4/b9eUebDBMg=,iv:1raYn3vIXf7/ntI1yn9r0nkqp/qjUEl0wu57DuAR1ok=,tag:kb0rQb+6FnUCn3qJC4STdg==,type:str]
      target: ENC[AES256_GCM,data:uHDhk6VOqDOSCIfPqHv98Q==,iv:qruFJN5ADpKlfEncirhX/z6+x7aNWfgh2aELAnbhgwk=,tag:itHfBMs31V7i6Ag4A7PCSw==,type:str]
      options:
        - ENC[AES256_GCM,data:wdtzEVLp,iv:vipHYy2/odZgBx5U383WGPgIF0gXiQmX3afR9K41LXk=,tag:2/9IN8rJ4iQWmry24baMJw==,type:str]
        - ENC[AES256_GCM,data:TYujOanS,iv:x0I49JcD4Yxwc0LEcODAnDchR80XGMfI7Myw37o+yNc=,tag:a97tzoTWtXwCEurWGqd23g==,type:str]
        - ENC[AES256_GCM,data:1xaLz2UNgw==,iv:xkiUzRP/Fj2Mf/f88E92tS7+7Bn7DHMQXAMrSt201Rg=,tag:uvLlcIZwzPOilvgX9+r+AQ==,type:str]
        - ENC[AES256_GCM,data:ATF4/A==,iv:Bg+kcgDKOGFHYi0I4a2L9c6/EGs8G2NrHH2OvLs1058=,tag:HvAkpdfcdkPJE3LHvsjaRA==,type:str]
        - ENC[AES256_GCM,data:IFWi/KAfBnA=,iv:2d1R8si3T+c/iZeNnLOfsxLnLy+JivQArRBOsGOJGGk=,tag:lkgrVyeu+RdSUT0u9kB1jg==,type:str]
        - ENC[AES256_GCM,data:7UbHs1Hk7w==,iv:aWNdvAVHgFN7TfW1PqLE1Mav3sX0C9uJrrb1Q5ohBbc=,tag:qsMW7jYbyTBM3aIP30QbhQ==,type:str]
        - ENC[AES256_GCM,data:vJ6gVDukVdVjeYziuWiFc5ivhg==,iv:IH0W/jEAQ2hxqY/XB+Xp6vIoHa7mN++BHwcVWxaB2B0=,tag:swmFcVd2cDeqfgpYiPAeGQ==,type:str]
        - ENC[AES256_GCM,data:y8i1PIjKcexKxuX/g//C1eWWu5CYYVfwaw==,iv:J1ZmBNfIPVIo5b3YqkEXLI3qKQhC9SQSuvUN425blUw=,tag:MWIjetnqIIOqJk6dJDYPqQ==,type:str]
        - ENC[AES256_GCM,data:ryA=,iv:ratVbqqYRK+F5Phj+cj/XqLeB7A0YczRc7vxBacmDNE=,tag:ga9N5RLfgP7cyMvmmvgPsg==,type:str]
      dump: ENC[AES256_GCM,data:JA==,iv:KSCHJcC8nFlTK4uGxCKuXOy/8DELWbt5UFiPi/mL0Vo=,tag:geCDO60mOeowVRRC2NLbMA==,type:int]
      fsck: ENC[AES256_GCM,data:Og==,iv:b4ES184HllP6MIerZ3vJCIJplCu7AmQoecej35XJOeI=,tag:Ausxhu6Wdk6NDeuN4qHJKw==,type:int]
      permissions:
        mode: ENC[AES256_GCM,data:gaTm,iv:+mXduk0hP9Men0efGtRODLyfZOTR1nWff/W5UALSxS4=,tag:hyGsqBy3wfuEnMOy+Ibuzw==,type:str]
        owner: ENC[AES256_GCM,data:NDmlAw==,iv:RQ66D549oe7C2EUIwE4qSl+NghwM11jMJoezbF+mZiE=,tag:dK6m7fWqJDrGOuzuooVr5w==,type:str]
        group: ENC[AES256_GCM,data:1CQ0/QQ4,iv:zkDSQ3lJt/GblY+Gpi4fK8DCG39ZN1w53nAHKdNvnVU=,tag:m/r+GQ7BSH0oiqTHX0Ej3Q==,type:str]
    - type: ENC[AES256_GCM,data:X4Jz,iv:3wVIJweZD6o3EHDquKeZiyA1z14vNbY/hR3chotoxrc=,tag:dC54OPuRyMEWAwfnZWdijw==,type:str]
      source: ENC[AES256_GCM,data:jmIwVimncJMkycSCzw81Bq26,iv:2dArcAn0se8nhrt0I6AfsnyQUQsZug5C4wjngzQJoWE=,tag:Nq8Mdoa10BZsnWwxvn/Wjg==,type:str]
      target: ENC[AES256_GCM,data:ZHUHtINZ+bENTQARTROXKfo=,iv:WfLGVPL4w7a/lubt5EfR9s4WRVO/i+/qCFS9OmzZXRg=,tag:HP3O30Gcp7/KYz49SPmvVA==,type:str]
      options:
        - ENC[AES256_GCM,data:sXc0QuiS,iv:aQ8qaRd0rA4wJlUScnADnMXTPN/LeKq12jGb5dsA1o0=,tag:pfjKbeMJmARZNiSKCHFzyA==,type:str]
        - ENC[AES256_GCM,data:6jKKtToj,iv:yFUB0Cjkaig/uh2ebO1yR519orb3V1p4q+35Cavq8F8=,tag:SuTcnH4GvV7/VJX2j7zhDw==,type:str]
        - ENC[AES256_GCM,data:kxSDz7nq8A==,iv:978yWiU0uHxyZLo59Jm3Gq7bKdqw2FLAUuD0bJb9mQc=,tag:8MYmqca21m1HNYP4VB4p1A==,type:str]
        - ENC[AES256_GCM,data:rMsCZg==,iv:eYRRoXPW3oNMt4DdeHitR3h9UidV3WpLeZcw4JN6s/Q=,tag:UFv6XKAyFhpLQOm4aavjCg==,type:str]
        - ENC[AES256_GCM,data:pemt29UeRnI=,iv:w+EjH1psqdljvSeEc3xsqaXZ/xBbPq6wuEY+SzTvp4Y=,tag:FX4xkhbeu1PzQvgodc4Avw==,type:str]
        - ENC[AES256_GCM,data:2/pU4XvRPA==,iv:sc+jMqvV8K3WcYX5FZRfuDoj9x8PgIdmWhCtxejXjKI=,tag:Os3y/B74CWbnhSfs6iB5ng==,type:str]
        - ENC[AES256_GCM,data:OSWwno8sR5fk5MInBDQb8Cvjjw==,iv:a884un0mLNu70qWs+2POrK8NK9WDTH7Xe0FDExZghzI=,tag:ZAM5pwfDwXxEF13VUpi37A==,type:str]
        - ENC[AES256_GCM,data:lw39sBXTQ5qAWEOWu78rHCInrXUxGCxMwg==,iv:FzMuGUlZOxo7NYVCXQBUjtBGBXIHOtaSazjGYjiHGD4=,tag:Xcca5FoFS19bCDnFQliqYA==,type:str]
        - ENC[AES256_GCM,data:qP4=,iv:ECqxpBzUJYgJKjUpg2oQSJSRmhyVGH/ZxAqS71+3F2Q=,tag:rhfXN7WEcETMc5mbhF3d8w==,type:str]
      dump: ENC[AES256_GCM,data:ow==,iv:n5YS6ULs5AZJO1WU2JBZsDFtUu4fzmFp5al4tiaTXg0=,tag:HOr0oUWXr1gix6ylJ1VsnA==,type:int]
      fsck: ENC[AES256_GCM,data:RQ==,iv:/d7FqnqH2hBNJJOnATYwLgv9h1oWYVauXAIcXmeTJ5Y=,tag:L8NCYY6ANHyABqksEpTAwA==,type:int]
      permissions:
        mode: ENC[AES256_GCM,data:F52y,iv:73NvCS0SJ/6cDFhnCDLUiUvSM2K1Sx/NdzaKVZUAYRY=,tag:mZIroE6ITRwlGlod7ZD9Kw==,type:str]
        owner: ENC[AES256_GCM,data:W9cV7w==,iv:BgtQRmHb3Oqvt1nElH/3BKATIhG3kmqVGwl6qHpQyeQ=,tag:iJREkP7OJi58BTKEmV+6Sg==,type:str]
        group: ENC[AES256_GCM,data:zwo/ZvAM,iv:QaAqBbcOSEkawMslSiVl3B23Tnh1cmI0n03xs1ai/xA=,tag:DlNtIfFAC6ktkJjSyYB89A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age172unqujv5uv885spfc8gk7ztru9y2lc3jgr20s3gpt9lzhtt8gusgzusdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyaU95R3p4VXFHbDAxUysr
            QlJrK1AzZHBQWUc0M0lYYmphRUdmT05oUnpZCjVld0JsN1RhcXBOUVQreVBlOXZr
            cVYrOTU5S3lDU3JabStmSXhORTFVSW8KLS0tIEFWQXl6OFIwMGUvRDR2UGlpUWZL
            OERYSTdON2FTYldreUErZEJhSE1vUzgKtjK6Gs2VubYsF+apdiL1TH5QGHEbASUQ
            vS6IYtldlsKS3cI3imEON8k6AHz36aIxxZXMuQ115s+yfYtGXurZQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13ae2q6s6f8talcfvvnzm6qzfhcecytr506g9xh6mnjpteecjd98qw9qvq5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUXZJeUZuTXhnVGYvUWx0
            OTBEdS9WWlpvdG41SUpHMjI0Z0pYckpWVm00CktKR1RwZ1JqanhTdGxkNmVhSTAr
            b2hZWnhUa2VjdkxWRHNoY0lrcGlGaTAKLS0tIG0rU3QzazZtZGZ5ODA0VTJZNHl3
            Zm9DR1dQc2NDRm4zOStrWGhvUlZBMzAKzcdKQQCnHjsvxqpnW4LUF1RqtGt/fPxv
            7qckAHtHLIA5snLr7Q4WlSqZGd3QZ5RO81zrw8KHV6VCfChr5Xo+WQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1nnza2w8tyapmnwm6gawae43j5nqxctqnqcy8xwe9n8czzcytxfmqd7m7fk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdGJjZmY4MEc2WmxvSWli
            cUlvZFNYNDZIQVUycDhNMlhYTldIaS9HWXdNCmhsMnJrWGJwcnhXL3ByRXh2UnhZ
            SzRWbWZGMlNDSEQ1c3BJcDFITFUwczgKLS0tIGVLcDdid2dDZVh0UjBTdFFwM3Az
            R1ZOaXVISzdRU0wrUnJWeEtJU2ViQmMKmdO1rQdLU+Q0l1lIH5gB1qSMOeO3A3+V
            XBYzuHc785y18BAV7Y4jTlZp03a++AP04k8nzgT1BRulEgw7nYdbNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mamwyuqtaw9xw8l6hxvy8v7uqe3pd5p7a749jpl3sxvt5pvawa8sfw8vz2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOWJVMWQvUU1KbTE5V040
            VjdTUWlGMmJUdHEyZms3NSszMWo1WjVhSkdvCkxwRG1Iam1nRFJHTVFUZ1RQTEFn
            Z3VvVXFJY1owcEJoZzRmYVY4UEhuL3cKLS0tIHZrbWJ3bWFyNmZCbzFWTmdrckpa
            aG5VVnNPdkJkcmJqWVlNSUQ4VHM4SG8KkWLJO3BwVsEwA80dVZTj5NPquTKdoq6a
            vRElWXGfTpdPm8X2Gy1mt4q4Q7MG6nC8rCFynbcw+WEKW4UZoN5c0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-03T07:05:31Z"
    mac: ENC[AES256_GCM,data:FCFBhzUi7Kzq0M4iAkowkbPNGOe7h02YjSMrl0S88Y09+S6/e19H92VoYLEicuz3k3HWGuaPujigreJ2zSlclQDtsWMYBqTsU7UnJiEro5qhA/UFoEz2eega4cxS8X9qXm6fTLtk66YD2WRvNkDhQvfLjGoaQ3SN8ht+EDuU+oo=,iv:sWQ8U6aVgIKNpqBjiSzRmsh4p+4mwPwURVU0u3exDf0=,tag:/sSj64F0Sa//P2/iLiAB0A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
