#ENC[AES256_GCM,data:BxtPCiI/VJlEZ0X+QhkyUz5GgO1RgTJgKzAf2i6ABSOlkc4o67HNqfigR3yuSFoW+YB9uo294SahEM2ixFYR8dAu,iv:h5QAkQeoZ8KHQoqvmeDdJqxSbtUVnsLaAngMvlY+CnM=,tag:IaYq5yoo58k3Nwu+hkDhrw==,type:comment]
#ENC[AES256_GCM,data:KJ/XhWJDKi5DRFt8+Ojl4jEc2YcLZTRuAr834WEGhApP6PrX8UihOgZRGHyE1DyQSyZCHg==,iv:zadM1vN4ff1ldMfw+aQfuTRIFsl0HeoP8ycPsOh7ZLM=,tag:LNgKOOSb871hg8EpenfgTA==,type:comment]
#ENC[AES256_GCM,data:s19CRIuV4YTK22lGO4UmKlVGOOttDDITN82KWyLi/XdJeqot2alPBFckkxJSC58PdYsBj+HJki6T6suInBrlSjMz,iv:+oJoCKQHPjSE05rsx0BFqJVgC+yI7+Ankmx+0Xxl/rw=,tag:DSW8IT0kyTslW/pZMYUnww==,type:comment]
#ENC[AES256_GCM,data:2t+/6MI9Dim4VmzSL1bfYWHKXTjNQCpPzPuvGRNC1TsVhkTIsJun/rUrZnHKzy8x0yPEqyRvtq7WyLAcIQ/U8ZA=,iv:VW9PEJ8acOZm3N5HhTWs9jVIqHxEksDI0C0Kgnd/fTk=,tag:hvOYG1HMm7+m0HwjPj6Hnw==,type:comment]
#ENC[AES256_GCM,data:1P998eoZVjeBLODthjrRtiT9Y+blvqZDfJOzqcD6hrygDg2CafH4YvElctu2e7sKoSrfjXPrspqSwAbyFPIZtpo=,iv:q81JV7xxWRu/tKkyOQZwES9EaEHy/5x2B5e/d8Kw/xw=,tag:AcgYXzgBCRIgdvuudrHT5A==,type:comment]
#ENC[AES256_GCM,data:DJOepR6CJ5sbO4MdnWLvXKba6A8srWPvlSQGDdc3fgsLiQqNpBBN69txjP3uyAMxtRmOu7LapPoFKIY/qtSP4LhZ,iv:AfPVOcLnUQ0KonJsqWWQJmOhJeBb6mlo801R/rShIBg=,tag:wV2xGXpaBBEbihIehN8PfA==,type:comment]
#ENC[AES256_GCM,data:8IsukjLW8Wz0U0TNL2q52CR2uHtgvhTZarwAffw1JyzBVNHY,iv:jGUT65tbUPjTx7s8GU1oFQi0NxplbCPzW6dGPNWtMqY=,tag:BPf9GcsgF9Sfyq8bGvUewA==,type:comment]
#ENC[AES256_GCM,data:BzmgJuX475M36Clt0bXoxkfvWpypVk0=,iv:GkwQYWifhB2Ge43e2qd2pNy4EkRg8MlygPoGZER4HbI=,tag:evllh+UK9MVeIlQg3+ModQ==,type:comment]
git_user:
    name: ENC[AES256_GCM,data:33wKsNv5tJbwEg==,iv:+XWQ9dAux5aXVNtMl7d3N/5z59bjB0U1/AExvfrBjbQ=,tag:FGwN/HhjAofFnrYmII3Dtw==,type:str]
    email: ENC[AES256_GCM,data:Ooi20RnX225qNZReBvrD6kI8QSZ6az42iizalCCoH1tuljQ=,iv:vIJOfw+D4YffqujZ/bLJzP5oUSASVma196BjDXz1xJs=,tag:7pSaUX0ebHGQJE4gSkTcZg==,type:str]
    #ENC[AES256_GCM,data:GsBdYBRuT2l/NVekSi7lWbQ087KXxjN/NO+ZlStBmVf7/13f+6DSuSmlF896p+vjMwcT,iv:gOXRc3zit0Em4JipdhHWhxhMkzlpZu1ZG8KzoM5l55g=,tag:rmEomi5vTX3KdsN3dBfv9A==,type:comment]
    signing_key: ""
#ENC[AES256_GCM,data:HR+J9aPqzkD8Byhl6guFAfP0,iv:GEs55+u4rUolQOhvw3omdgsohEgvfkFvqUyckZRDT48=,tag:cHSmJ1Rfnr84Wc2pap90VQ==,type:comment]
ssh:
    #ENC[AES256_GCM,data:Cm/93lnFEisXrcTRgsMYjPnG/ZrRlmworW9AZYW7p7Z5TC8Y,iv:Y8nIO5eDSalXFy1P/dpqwGFg+zKB/6ut1Is+0RC2jF8=,tag:SdArWAMEp6ut/ZXDWnt8OA==,type:comment]
    generate_key: ENC[AES256_GCM,data:rVmrkg==,iv:jFug4F8fOypdEZgLcK2kMdoaUHUJI+H61jaIwLx2BKw=,tag:MhChRXjEW1RNOmuIzhPC5w==,type:bool]
    #ENC[AES256_GCM,data:zA99aPR7DQCtyvGet9gcAjw0IjKCOw==,iv:ITdfAoyEJLmVh+V7dVu5pEjdrAuTTUoD0G7rl7KHZ8M=,tag:2BShrpT9O1NdHHgeAcN5Qw==,type:comment]
    key_type: ENC[AES256_GCM,data:hDp00NFzQg==,iv:wF3crOSldlOALyhrQ1uIV1GqrOU817xoqrsd4Arj5uE=,tag:nWjFf0DxcNRU48uR5/uZdw==,type:str]
    #ENC[AES256_GCM,data:MeQKwTNKwpkFCFoMRTTobvL2P6Y2ug==,iv:S143GjxsROiZcvrT18ce2wuQQSkJ0ntGWP+tenkXE38=,tag:ors2rw2l/KjdK5QQakSqdA==,type:comment]
    key_email: ENC[AES256_GCM,data:uQ+W6P0dtpdBEl3f4jsQ89WP3ldG,iv:wnaKA8IQvsJ7SrO7PoBRYNSCDtB3fVxGe6RsOh5smEY=,tag:98K+1VfFJtzixfB4oV5h1Q==,type:str]
    #ENC[AES256_GCM,data:stLjrJLinN0etD7MXB0fKgNTXJmhEuEM1a1ONu2WS/+MH7reHyFkEwpdudKaHFYqFyNENJkKjzoi8SI7T60x/Q==,iv:DUdxCPpkWYlTXvKJy6WLsSJq00RVne/ByQ5vecIxIf8=,tag:Owwqbrr4F3HC3rtGiQtRnQ==,type:comment]
    key_passphrase: ""
#ENC[AES256_GCM,data:hMEPj2hqiKIrOzVkm9sRh/ju64QM,iv:rRW7CK7ou4NmCXkOpsdwJU4qtjqo+1tmUXhXvkp9TWE=,tag:MheSpd5GDjgyi/pHmUEvoA==,type:comment]
github:
    #ENC[AES256_GCM,data:XvA1VJamOvsPwm9ms5Co+fFaLc70,iv:SR1V0Wt2rxKt7RuaJ6u28dkCIahniUfObZPPXVAX1oA=,tag:JVld1y06EYyS1RM1Cyau+w==,type:comment]
    username: ENC[AES256_GCM,data:pNibHLEMZJITRA==,iv:Fb6Y1wFc4g7wEl840QepAcnWzJ1Y9PHrbgmtOE813j0=,tag:fRClqr04ewMlEIh7Ez/8NA==,type:str]
    #ENC[AES256_GCM,data:A6T7gep78oCgUGPJk+S5nNke6bRqwrGtwrSqqGFJ/TbNzc+RA5NHqJg=,iv:uh2ADri/ThsXn+lyZL8RZPY0/LTPo4mcFRj/SrYKTTU=,tag:/Yf8ffhBN2O2vhrcGlGMvA==,type:comment]
    upload_key: ENC[AES256_GCM,data:Z5CysA==,iv:Je4+ozXAH1doNw1+JP86AA/k0sB3xJ9mIK6goiYBOo8=,tag:smNN2AceD4mP045xAtTTVg==,type:bool]
    #ENC[AES256_GCM,data:XdQwCE0k7qc1aF1+kJDS9KysJvggP86d6ElBwP6EJ2j3zHDe7HXyKx697U/UTCYIjxDe,iv:nQPL8H/LQPGHR+GyuMwgbSVwHF3SwCs92r5uHq8aQI8=,tag:V/6nqcI2zBxt7U4g7RSygg==,type:comment]
    #ENC[AES256_GCM,data:fWk9aDgNKyesnWFET/YT73oL2crQI5kiKnkStfeRl30qQSVe,iv:7F+mxpI4uEg9heW44bzS3OtbOWTAHwuiBoYc32GSxRE=,tag:OY2LgCKwwPtU2wNicEKNtw==,type:comment]
    access_token: ENC[AES256_GCM,data:9W2WINZrBW01lg0O5iAxASzzq4P02IyKoHCIVFUPdTGriIl4cJeOkfUxQ5yma8eToH+gi7TJw1bD0dehONzq8DBuMRO453gJnZnjQ5S9/rG1tiSr18ZbOvNxWo8T,iv:d/EoQ3C2hn3jMwQuW6N+8OVaMI3c3dmEu5/iWn2nVKk=,tag:mpTFjBFpa934l/Cpn5hX3g==,type:str]
    docker_repo:
        #ENC[AES256_GCM,data:VYUgCKUbzex0q62n7uXvXNtF5chW/s8P6GD7kb+UuVzc7ZMYFCQ38lqrqhkE8v91+XzWm1epI/HRNoWzEJh4a/C1cgdc8g==,iv:f3mb25i7LFI9rasUeybA3YJhgrSddRmc9dgfvaMVXqY=,tag:1am59Cvu9WqrJwIOJ/eEsg==,type:comment]
        url: ENC[AES256_GCM,data:QlnFG5TNm57/HY/WMH1+pUyKD8aipqDjOiTB0tD5NT8r4fOdafmNkM+2JARa+A==,iv:+IjJThVi4NP2OhTC+7ea0taZxOsMi12lwmLCCa84NOk=,tag:e/bPqHJWoEGE1grg0lL2yQ==,type:str]
        #ENC[AES256_GCM,data:cVzG5Y9yQb3pq/co00rF2U3msZdggO83zqjE643tIdJv2YBJwSJmx0xARnizogQr2w==,iv:FK5CTneSfi0mq4Ja27mjpDjzvS55jhBXHNXj1NTXXzk=,tag:kJC32v1EGnZ1+93FT46KVQ==,type:comment]
        branch: ENC[AES256_GCM,data:zj1j0g==,iv:enbl9TTNZOPv1fzazozCP1oPJSZSWmo3bJNPQMktLJ4=,tag:PJhH685ffKsamZi4drV8Dg==,type:str]
        #ENC[AES256_GCM,data:evzkLp/HqmjzXTptlhXGOuem9dHWX05mrVTodxORd3XDVYLc38RM+1MnlAhUy5G9SylLdw==,iv:KYovh5eYs4bq9nRcsoFBySNf58T10w1ryBeYFyym16M=,tag:aPJ9ml5plXcR5hNRfryzzA==,type:comment]
        #ENC[AES256_GCM,data:d5MPQV2EYv7vzdMrh0hxpQEkYCjWAQfw0RxO3p/aKNj2QJtdWWX4gLxdNbp+2Is9/W8fnSh/yRUdcQ==,iv:4kBictVqNzPbRbR8sD0IDlmjwcZZnCxsJdo5z76zKwc=,tag:SiB6NafB7FRawunHbVc0Ig==,type:comment]
        directory: ENC[AES256_GCM,data:r7OdXKwKdnurgD4C0Q==,iv:eHkWZCTuLwdextlClmV7ZBiiKfbB4Wdfv6Culwcy81U=,tag:bbm6mLHji3vqoP5qKRvwLA==,type:str]
        #ENC[AES256_GCM,data:zawuW6pTQ5yc6MH+3kMx5tPJNuDJmkYNYVwN8umrX4M7iqLNKYy30VEESqOpD6d6ZsA3lJFNXlNMdGPfbdvVOrnG4sU=,iv:ohK0G6qXLFDpeech33/kWRTioQ3TzwLl26ZYvn1eaOU=,tag:3Ij2MniCs0f7YPndRXqvSQ==,type:comment]
        auto_update: ENC[AES256_GCM,data:F8mcNw==,iv:0v5RtMicy7fXx+EqK0njCWbe+peTwtWvRlT+EgbWFMU=,tag:uVW3WYpM2JooOXyuZ0IQNQ==,type:bool]
#ENC[AES256_GCM,data:C8gaa/1RPVdq/6BKufjn,iv:5KDAZDQ3Go4+nzSAFpKwcUopSMPqnk/C1VMC81/PmH4=,tag:IpAIDgrbO2Ieh3m1kBzD4Q==,type:comment]
network_mounts:
    - type: ENC[AES256_GCM,data:8DY8,iv:qWEHyZog3OeWYWkbKRoTLcqyod+fL5jXdkpOksrid2w=,tag:bSw33XKuHSgyoIhTPWmFYw==,type:str]
      source: ENC[AES256_GCM,data:WSPgudPZMaPMw9BTZT4clIr6QkiE,iv:dTvv72jq1RV25KBs/GyTn336j+CsNmrAESOnIAYjSn8=,tag:d5nJ3Oy0xOBk6XMnrAhX/A==,type:str]
      target: ENC[AES256_GCM,data:YVFL+mEQaFS+o6M=,iv:8KBQlHPXYgsDuJeDHhuuEvkFYwGp4tdPG5lk9xM47fo=,tag:R7agaFSoaARMk3e2PlFT9Q==,type:str]
      options:
        - ENC[AES256_GCM,data:vtmr0oUI,iv:nHTHtJHygt7LQ8iERstPvdDEFokVnU+pmPZd5enlQgk=,tag:w1L6WHZVtDNOlT3lx+PafQ==,type:str]
        - ENC[AES256_GCM,data:Z0uRKU20,iv:2cASH2FntP+/M6pYvUngfMZj7VULc4N2RVA7jrjmP9I=,tag:RSFO3sfCgALlt0mzuS4bWg==,type:str]
        - ENC[AES256_GCM,data:ylddHnbtvQ==,iv:1JpDBLPFXiURGGBKMK7uzvrLwt5T5lPRFhGiwGlABxs=,tag:p3eHXwea3VmsVLao5oMP8w==,type:str]
        - ENC[AES256_GCM,data:Q5z7KQ==,iv:a/XQelS9j+scFh5cwFmQ94brSJ/ih9JXR5tnwckmmpw=,tag:kaRh1EdAH3JvT7Ze7WI3xA==,type:str]
        - ENC[AES256_GCM,data:AV6RZ6d8L98=,iv:LPJExPCV5TKKVPZFscvjbSqUH/jOceHUjvoQ0prNOgM=,tag:bZzODpNEJkq+H3GkEx3kLA==,type:str]
        - ENC[AES256_GCM,data:sUMweu8POg==,iv:O86/seH+eF4hNnZqeGZ3vFQeRYytlPAE81sKsGCQ4oA=,tag:jxvfgFm9kZBrOoCcdhSA6w==,type:str]
        - ENC[AES256_GCM,data:VYn6swpUJEhszMico5+Y/+qlow==,iv:CBttEZBJeMnwQHh56ZIHK0Us2TLf0GIjYel7WnkfBnc=,tag:cDJeq/04fmKd98A7sOVG8A==,type:str]
        - ENC[AES256_GCM,data:hhC6xRsUPQXM2jUnDQVJkwawWo5vELpXWg==,iv:LCEwu3XvHhbNem1uOOkkqteHUVjhH8fDA0dATCTLhrM=,tag:qvdBjI+v1h03ogtc2JSJJQ==,type:str]
        - ENC[AES256_GCM,data:g5E=,iv:XCIzd85UOONgM/BZ38DYHsu39WLo2/xCHQKFmXykRNI=,tag:GtE2+nNraOpHTMbWdZ7nWw==,type:str]
      dump: ENC[AES256_GCM,data:mw==,iv:FtnF1OkW3hQmFXklYfbjt7W5FSJn/HjaCfanvyA+ipI=,tag:lin+xFx3jZSqJEyW2fvpZQ==,type:int]
      fsck: ENC[AES256_GCM,data:tg==,iv:ZcbMbNrEA/PTkj8/PuM/lxxFqXisB9xJtA6SmhDlDX4=,tag:sM5imZgK0CKP7E9VRjX5pA==,type:int]
      permissions:
        mode: ENC[AES256_GCM,data:easJ,iv:zOvicLzbSmzYK32P3QOFFfDExfJKlAkRbHG5PsMqU4w=,tag:wmeuIPU08MtdkqvfCOE4SQ==,type:str]
        owner: ENC[AES256_GCM,data:agCJNQ==,iv:Z+1ME+BEWHkeS02vbBq5VpbvHa0fHxrq+NhuvJfFDOg=,tag:oeMZETGdPQ5BratqVXyM5w==,type:str]
        group: ENC[AES256_GCM,data:qppl4JYj,iv:yooaPBM8crjAQx0Fl9inXjq2pt7+ON9UeNBJuqEKkEQ=,tag:vRdoPml/BzPkWdieOjnWpw==,type:str]
    - type: ENC[AES256_GCM,data:yV25,iv:vK/h1/UYSPu4U8yAXtpBMDXpT42zGgtmR3lozVRXrmU=,tag:SMWgRkF/oUK6zBx0eWq81w==,type:str]
      source: ENC[AES256_GCM,data:VAVzmyFTIOPCPsvN/AAe5d4MZVcyqg==,iv:8f7SzrBGhm38egx9+6o5pbU17Pj/QpP7E4Iyr19mdyk=,tag:YFNFf/qvjmsvOzPdk4WsfA==,type:str]
      target: ENC[AES256_GCM,data:CztDxqDA5oTvbuSc,iv:rHigRbydL2tsrEChZ8yBP76pkMKyg6x3OTIVk02/hXE=,tag:I4E/kur3fPdRzYfjZFi/Tw==,type:str]
      options:
        - ENC[AES256_GCM,data:/4INTC9R,iv:oxM7/8Vk6M0Ac0QzkMKvpdoIjnFsK7xc3D8GJmQR76g=,tag:MCkz9fZ/vicwRVeEGX7lng==,type:str]
        - ENC[AES256_GCM,data:sTu4j4vk,iv:X9quek5P7oeok+KHZ5R3UUKSF0P7KoTBXRIZsXVgnLs=,tag:tteMj2/ENvZ9nQOCrkvdgg==,type:str]
        - ENC[AES256_GCM,data:8c7ZbcXGPw==,iv:F02blw5sjUKxVtSxUrpIx7Wg1zpAOdXIOSTvc4SXl3c=,tag:rmfHNsnOgEZaa9go5AQ4GA==,type:str]
        - ENC[AES256_GCM,data:aNdI5w==,iv:KeOaxI9+6ZiiQxE0MgxGA7oQ5233ciSSPLvzuKg5WOs=,tag:NQ9X3xDuK5WVe1cXRuqcMw==,type:str]
        - ENC[AES256_GCM,data:NuEvM+IE3ZY=,iv:FzfsjRj9O4I4LtwlWUtrSCNaLwwhkXY//9XXXn4YsaQ=,tag:lx+KO4hqznnpDkfC8C5FuQ==,type:str]
        - ENC[AES256_GCM,data:OKnvWdzenw==,iv:rTtpd0M8Nf/fFyLmyd4wgQGxNcE8NDCpLCjWFwKyh44=,tag:aYru9p1z1jJ4oLKbrVU0Aw==,type:str]
        - ENC[AES256_GCM,data:tHDbK9mcvaoSRxmWGe5WJx+qLQ==,iv:fLpG2Z5Ef+ct3lgemz+yKMMu5v7zlhLrl9l+9g7fy3I=,tag:TKVPV33cYXfEpQo+6F6FJg==,type:str]
        - ENC[AES256_GCM,data:uWrcjCrXKaDIDof78drrRoTQBo6QnMujmg==,iv:r2ScwW+lv1pWJPUW6OkfROptX0Pz3Mlu/YFWQ9w1hrU=,tag:8OdLGfEGwLF/3M+xfJjEcw==,type:str]
        - ENC[AES256_GCM,data:rbA=,iv:uqk8gZWa16hnLCS3xeSfuxxnHqljLfxiHlhaiVOBwZk=,tag:qBapCpt4O26DoK7F4Yip7A==,type:str]
      dump: ENC[AES256_GCM,data:kg==,iv:JszTvZOcZgAZYZaE9mnvPPfxCknWgmn7dxPwlNqRwjE=,tag:zGt2/dO8EE2v27UvteqKoA==,type:int]
      fsck: ENC[AES256_GCM,data:Jg==,iv:5NdTVxdbdDmxxZApwY8ifk+tbryxy/iUvxqSInaFGbE=,tag:WCKQojYKZlYMDxDBjmx/Bw==,type:int]
      permissions:
        mode: ENC[AES256_GCM,data:oex8,iv:/Efo0Jlk11L8wtUdD+f558m9CDHn/ztXc3bN2yMBdN0=,tag:joZVIw1HlJCStAw6Cgi31w==,type:str]
        owner: ENC[AES256_GCM,data:9kL3BQ==,iv:5swISNtdxu+ubVZsm1CqEPXLWMg7tkPsa6+cTUFOReA=,tag:CDFrhwZXrreh4q1TpmTQlg==,type:str]
        group: ENC[AES256_GCM,data:LT70959x,iv:hZ4z2wTb86g7+P0P7mPkDhRSlB20bGRylNCGHyZV3LU=,tag:yQzsLwFYdwidxCNwK4upLA==,type:str]
    - type: ENC[AES256_GCM,data:bEL2,iv:khbN0aVtH6fDx+FSZ3xE5c4wNNzaRbm8ApjlSexik8E=,tag:deF+5hC1/FS58CgWAEmxbg==,type:str]
      source: ENC[AES256_GCM,data:2WB2LN6bw2rNf7XWimuM/z4=,iv:6YWnnenhYNOEqkkHDDbhQBu6fg+YenF8zym8Hq9TELs=,tag:tDkvTm/1r+VsDWqfPlhyPw==,type:str]
      target: ENC[AES256_GCM,data:IlBTZKLFmXPk66fxhczmngGv,iv:hyn4pS8xTb2BymYS14Z7u3qUUkgP3Ku5PEZXMaJzoLc=,tag:27yi8ZbYhNhUXYFgH6Pq0A==,type:str]
      options:
        - ENC[AES256_GCM,data:iG4hxeig,iv:v8dfENS4M1EDhvSP/vwTUwkaRTrMh9N+YXE/9VPgesE=,tag:hLJ+sKdCRw4XDBqzC0qa5Q==,type:str]
        - ENC[AES256_GCM,data:NKhzG5bf,iv:gM42tIwfdU/v7j3ru0WH4Jlnz5knwBtNs4QZUwFqW5o=,tag:aYy1qq4lav6ngPcOi8ZwRw==,type:str]
        - ENC[AES256_GCM,data:Nt4V8g6iXg==,iv:zyT2UdQIm7PEhVMLj53RYCgj+qkeHhUJMbSmCquL1e0=,tag:OuVAoAFD/W2dscloX5cqcw==,type:str]
        - ENC[AES256_GCM,data:nAuhOA==,iv:aUEVsJzGVLkC9FKkTTyrNxQ35bSfVrbxlIVLzuNEa6I=,tag:0cAEpw5uBSZVWOFRiyTgBw==,type:str]
        - ENC[AES256_GCM,data:BkqfExx1JZA=,iv:5Su9vkIwmFRby1HVN3rYALQ7Xz+33N4f3XvtuanVanw=,tag:QeUce/C/bBofZOG/oOfNlQ==,type:str]
        - ENC[AES256_GCM,data:fWhgKKi4mQ==,iv:Y8NMOsZObOapQlphadlV/29giQ5qWc66wlaxcl2mo9A=,tag:g6mJCMakE13MjjbXwNQucw==,type:str]
        - ENC[AES256_GCM,data:4JD0c5myH1Bt5W0zVqpFojhOpQ==,iv:K1nGR0GQId0aX8xASm89o5J5wU7zD2AAyO38k8hjVkA=,tag:RB9bcP0LRXaYqsLkhNqz9A==,type:str]
        - ENC[AES256_GCM,data:AhrwjleDheiE6sgWDMg6xhTra59bw1zB9Q==,iv:xYhkPCwN0efuNJXqu6cwQknC1b8VaZYkzxTdwXcEIAs=,tag:k/I/pk0FQKpPqD6BsG5I6w==,type:str]
        - ENC[AES256_GCM,data:pOo=,iv:sZzUV/sd53wDLvJCAi4TXfbJMoQJQ4p6WtLNuvdZ45I=,tag:1ExLHH74xYkl94vWla0mow==,type:str]
      dump: ENC[AES256_GCM,data:Xw==,iv:TKzFjfQCZR+zG6/O5k45wRcqusFJcgXTNgCWqtj8J6A=,tag:A1HwT2fR9YTYFdSso+I8Kw==,type:int]
      fsck: ENC[AES256_GCM,data:Kw==,iv:G3jfkBXzoNglpo0LEt9qdS1kU4gc3qdPPh8PqDT0o6g=,tag:EtiWE9vwIfxzhO3w/q11vQ==,type:int]
      permissions:
        mode: ENC[AES256_GCM,data:S9IM,iv:XNUdDsYmSz01VyzPz4WfblIOcsY0bjjVH4VVcAX+PxI=,tag:yK6PmyEQ+uKR+iP8kxXg0A==,type:str]
        owner: ENC[AES256_GCM,data:91UrQw==,iv:OY5oPjKzacCYpFz0yVkD7B0UnG/0t3AxwnHPXZ31Kv4=,tag:WKZW3C4fphnvH9+0qX9hTA==,type:str]
        group: ENC[AES256_GCM,data:Js9Jp5kI,iv:tDG8gJfoqNnVdYsxBbGfFrjjao5eIJea35GuUoay8M0=,tag:xtB4goh6gQQcak4S2Abf3g==,type:str]
    - type: ENC[AES256_GCM,data:fIon,iv:Kio/k+4k/Dh6bmUrYxOh7wQCTKOIDLww1K0yEBv2hI8=,tag:kHEbIGemh/qOgWnDR1PTyQ==,type:str]
      source: ENC[AES256_GCM,data:EBFhKFJe/25P0kYyJHSdEGIH,iv:8x0syiiffkKokK/zc8uyRHJ5necVFtmVfTB6RB/Sjdg=,tag:fCRS5HBD9glAqNlmgMR2Ew==,type:str]
      target: ENC[AES256_GCM,data:7aOb3Ml7JYVlvdi/LqCpmwyw6g==,iv:YNBSXZzA91EZJ1gLEZhBpsHVdAWHIASbLabnSFqQdyU=,tag:k/IbfUkIVJldKGNSEXsseg==,type:str]
      options:
        - ENC[AES256_GCM,data:nQSRfl22,iv:pdZUAkpBGYzMmmXzi3MpIae92KJj36GcPCZ9vAcIwe0=,tag:L7hU3O3lTNezAiacTZG+eA==,type:str]
        - ENC[AES256_GCM,data:E+EJJlmQ,iv:UimVzyqW76ZkYeMHtpvSNEoW7xQSX94ulcAsKVF0aOk=,tag:S97n8JcTh0eqg22ZcwMqWA==,type:str]
        - ENC[AES256_GCM,data:3hXmUPtEHQ==,iv:uzabTsWDHkV5yiVWjm3oJ8MP3pM3F9Gyj4kM03Xwawk=,tag:7ZfLdlrlxPsfNJpnG4kSuQ==,type:str]
        - ENC[AES256_GCM,data:pi+rUw==,iv:j2FZs15xWx0s7rJA19FnIgkYCrVcSyeySffr7WynWlA=,tag:xPC+sVfFE9t9StdfbYnMcA==,type:str]
        - ENC[AES256_GCM,data:lCSinfszfKk=,iv:RdM5y3Ii1m/oZfrOZHEJbNRb+QmQkTUe1o1+MvjOGLM=,tag:idLCM/4kU4vvVBLbo+LGOA==,type:str]
        - ENC[AES256_GCM,data:4R2n2jw6aw==,iv:cgKz5FrrIQasjc4uRE09N/8Zy4Z3UdLSNKq/vHMVZ5k=,tag:kfm/ZE6lh0hbxJxT0IZdmg==,type:str]
        - ENC[AES256_GCM,data:qyTX5lrv1oy7nw3Md+4z2Lwchw==,iv:KWgVt8t73/L3oAk1+maQtZOwCp4z07C2qQubAKemVUM=,tag:gu4h1RxrhramS38v///OQw==,type:str]
        - ENC[AES256_GCM,data:WIwro7OFwZcxmmSbe9SeBaOtZrPvmpWvtA==,iv:CnLPLirUeut0It/PQahCtC4b2gdT9FYDe8or7XdyjEA=,tag:/JWlbWSABkcD9sz2ThrtvA==,type:str]
        - ENC[AES256_GCM,data:FSw=,iv:phqSm0KviBgzocAmC7sEePSEsdScwKE8tYecNcClkRE=,tag:Qe3uuiFNpUC/GSxnICrpLw==,type:str]
      dump: ENC[AES256_GCM,data:fA==,iv:Ib67hxb2Z4j5YkofiVO2/cod0CRc1ftFJLmh4fQmpFg=,tag:wapFzSIwBUqXdN+rzniisw==,type:int]
      fsck: ENC[AES256_GCM,data:QA==,iv:sDoULBKDv5AM0ExpUWiNYEZfy4XDqb6W5MBcHgMxn4Y=,tag:Ca2SjqNhaXyK19RxS27mbw==,type:int]
      permissions:
        mode: ENC[AES256_GCM,data:5nvP,iv:Hc9csxorRAiYumMIKCVlYZHuknz+FT38OUL0Ffrg3OE=,tag:tIC4fbNdNtTYGqqjVvKpyw==,type:str]
        owner: ENC[AES256_GCM,data:SUC2NA==,iv:ze5DX9wXgmF9CngJQF6o/gHENru3ba6y4MUiokjiFqk=,tag:bJhWcuh7SuupkBHbh+Pzxg==,type:str]
        group: ENC[AES256_GCM,data:NyVx+hmX,iv:EmzuiAdWjbRUGIvLGXN001aDaAXUTronuj1squb+UWo=,tag:MQKXT1cJhKinfyzDpKCqTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age172unqujv5uv885spfc8gk7ztru9y2lc3jgr20s3gpt9lzhtt8gusgzusdn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VFRESVlZVUk1a0tDQk4r
            c0FzUFMwVUhxS3hvSk1YTEo5aDJIRWNGUUdvCnlnYVdTdzdvbCtnMnBndHhOOU9N
            d0ZURUNuVThvKzVLSVBTWVdmTm10eHMKLS0tIHlKejltOVczaTUxUHhROVB5alQx
            UWo1MmpmVjZRanF0TnBMQncwR1NKRUEKYf7u88c9j5F7hlYJVAgCVCOAjNhMmLlR
            ZOqi9GMX+q48YUTiPUCIwZ29a8vy/tbtr+7430DLO/NtAb2/CzVeKA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13ae2q6s6f8talcfvvnzm6qzfhcecytr506g9xh6mnjpteecjd98qw9qvq5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvVE9uUEQ4Zy9KZDY2bVpk
            WUpVc051eGF3NzIvcXVQaUdmNWJrUjhnVEZVCmN2V1VzTVpLditYV0NISVFTT3ZB
            aGhvQy91Q1pObmZqanRZTkxNU3ZpY2cKLS0tIE4zdWRGdzdHUWVuSnQ1Q0NRbWpU
            TEtRam04Q25XdkdieDk3ejN3Z1gyY0UK3YPeCtKs8ijqZP7LqOv4S8QKMrTaQSzz
            NzTFMkOQxe4V0gSeVhUT9CAZUMM9F+q6nsMr3YXAfNwH3khd4tYdQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-13T22:35:16Z"
    mac: ENC[AES256_GCM,data:4eEVsaw0GzPmNUwerdDm51mR1s/Mtg4yCIk1aE5/cztvNSvPAbZcCWUoghp996Fp9Mve6tXqQdfWoDHc0kPXb1JxKpvzi/EkNWKOxqHYQ9C7DsYmde4hpq2nnFgKV+oO0EOK2DBS6/IEil7b5svIA1Xl+GUL7tG4sroJ5yFq8xo=,iv:0P9kacTWZgt/Pcdsg0YEWh8qlOsWLqVxSy4vH0Xft+M=,tag:GWQb5/fxP9LJlVUcdz2t7g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
